/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -IC:\Nim\lib -o c:\users\dansm\desktop\folders\robotics\field-telemetry\nimcache\stdlib_times.o c:\users\dansm\desktop\folders\robotics\field-telemetry\nimcache\stdlib_times.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <time.h>

#include <string.h>
typedef struct Timeinterval107407 Timeinterval107407;
typedef struct Timeinfo107405 Timeinfo107405;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY107548 TY107548;
typedef struct Tfiletime104245 Tfiletime104245;
typedef struct Slice88061 Slice88061;
typedef struct Valueerror3449 Valueerror3449;
typedef struct Exception Exception;
typedef struct Tcell46746 Tcell46746;
typedef struct Tcellseq46762 Tcellseq46762;
typedef struct Tgcheap48616 Tgcheap48616;
typedef struct Tcellset46758 Tcellset46758;
typedef struct Tpagedesc46754 Tpagedesc46754;
typedef struct Tmemregion28610 Tmemregion28610;
typedef struct Tsmallchunk27840 Tsmallchunk27840;
typedef struct Tllchunk28604 Tllchunk28604;
typedef struct Tbigchunk27842 Tbigchunk27842;
typedef struct Tintset27817 Tintset27817;
typedef struct Ttrunk27813 Ttrunk27813;
typedef struct Tavlnode28608 Tavlnode28608;
typedef struct Tgcstat48614 Tgcstat48614;
typedef struct Tbasechunk27838 Tbasechunk27838;
typedef struct Tfreecell27830 Tfreecell27830;
struct  Timeinterval107407  {
NI miliseconds;
NI seconds;
NI minutes;
NI hours;
NI days;
NI months;
NI years;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Timeinfo107405  {
  TNimObject Sup;
NI second;
NI minute;
NI hour;
NI monthday;
NU8 month;
NI year;
NU8 weekday;
NI yearday;
NIM_BOOL isdst;
NimStringDesc* tzname;
NI timezone;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 TY108054[7];
struct TY107548 {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NI8 TY108073[7];
struct  Tfiletime104245  {
NI32 dwlowdatetime;
NI32 dwhighdatetime;
};
typedef N_STDCALL_PTR(void, TY105625) (Tfiletime104245* lpsystemtimeasfiletime);
typedef NimStringDesc* TY109239[7];
typedef NimStringDesc* TY109255[12];
struct  Slice88061  {
NI a;
NI b;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror3449  {
  Exception Sup;
};
struct  Tcell46746  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46762  {
NI len;
NI cap;
Tcell46746** d;
};
struct  Tcellset46758  {
NI counter;
NI max;
Tpagedesc46754* head;
Tpagedesc46754** data;
};
typedef Tsmallchunk27840* TY28622[512];
typedef Ttrunk27813* Ttrunkbuckets27815[256];
struct  Tintset27817  {
Ttrunkbuckets27815 data;
};
struct  Tmemregion28610  {
NI minlargeobj;
NI maxlargeobj;
TY28622 freesmallchunks;
Tllchunk28604* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27842* freechunkslist;
Tintset27817 chunkstarts;
Tavlnode28608* root;
Tavlnode28608* deleted;
Tavlnode28608* last;
Tavlnode28608* freeavlnodes;
};
struct  Tgcstat48614  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48616  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46762 zct;
Tcellseq46762 decstack;
Tcellset46758 cycleroots;
Tcellseq46762 tempstack;
NI recgclock;
Tmemregion28610 region;
Tgcstat48614 stat;
};
typedef NI TY27820[8];
struct  Tpagedesc46754  {
Tpagedesc46754* next;
NI key;
TY27820 bits;
};
struct  Tbasechunk27838  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27840  {
  Tbasechunk27838 Sup;
Tsmallchunk27840* next;
Tsmallchunk27840* prev;
Tfreecell27830* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28604  {
NI size;
NI acc;
Tllchunk28604* next;
};
struct  Tbigchunk27842  {
  Tbasechunk27838 Sup;
Tbigchunk27842* next;
Tbigchunk27842* prev;
NI align;
NF data;
};
struct  Ttrunk27813  {
Ttrunk27813* next;
NI key;
TY27820 bits;
};
typedef Tavlnode28608* TY28614[2];
struct  Tavlnode28608  {
TY28614 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27830  {
Tfreecell27830* next;
NI zerofield;
};
N_NIMCALL(time_t, fromseconds_107477)(NI64 since1970);
N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b);
N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b);
N_NIMCALL(Timeinterval107407, initinterval_107614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years);
N_NIMCALL(NIM_BOOL, isleapyear_107630)(NI year);
N_NIMCALL(NI, getdaysinmonth_107645)(NU8 month, NI year);
static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NF, toseconds_107658)(Timeinfo107405* a, Timeinterval107407* interval);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NF, HEX2F_87999)(NI x, NI y);
N_NIMCALL(void, HEX2B_107808)(Timeinfo107405* a, Timeinterval107407* interval, Timeinfo107405* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, HEX2D_107821)(Timeinfo107405* a, Timeinterval107407* interval, Timeinfo107405* Result);
N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, Timeinfo107405* Result);
N_NIMCALL(void, gettzname_107546)(TY107548* Result);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NI, gettimezone_107604)(void);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(struct tm, timeinfototm_108068)(Timeinfo107405* t);
N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b);
N_NIMCALL(NI, getstartmilsecs_107609)(void);
N_NIMCALL(time_t, gettime_107448)(void);
N_NIMCALL(void, getlocaltime_107453)(time_t t, Timeinfo107405* Result);
N_NIMCALL(void, getgmtime_107459)(time_t t, Timeinfo107405* Result);
N_NIMCALL(time_t, timeinfototime_107465)(Timeinfo107405* timeinfo);
N_NIMCALL(NimStringDesc*, tostringtillnl_108637)(NCSTRING p);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, HEX24_107494)(Timeinfo107405* timeinfo);
N_NIMCALL(NimStringDesc*, HEX24_107500)(time_t time);
N_NIMCALL(NI64, unixtimetowintime_108680)(time_t t);
N_NIMCALL(time_t, wintimetounixtime_108688)(NI64 t);
N_NIMCALL(time_t, fromseconds_107471)(NF since1970);
N_NIMCALL(NF, toseconds_107488)(time_t time);
N_NIMCALL(NF, ntepochTime)(void);
N_NIMCALL(NI64, rdfiletime_105604)(Tfiletime104245 f);
N_NIMCALL(NF, ntcpuTime)(void);
N_NIMCALL(NimStringDesc*, ntgetDateStr)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x, NI minchars);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, ntgetClockStr)(void);
N_NIMCALL(NimStringDesc*, HEX24_109234)(NU8 day);
N_NIMCALL(NimStringDesc*, HEX24_109250)(NU8 m);
N_NIMCALL(void, formattoken_109266)(Timeinfo107405* info, NimStringDesc* token, NimStringDesc** buf);
N_NIMCALL(NI, hashString)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_76643, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(Slice88061, HEX2EHEX2E_109273)(NI a, NI b);
N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_NIMCALL(void, insert_89801)(NimStringDesc** x, NimStringDesc* item, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr);
static N_INLINE(void, rtladdzct_51804)(Tcell46746* c);
N_NOINLINE(void, addzct_50217)(Tcellseq46762* s, Tcell46746* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, format_109392)(Timeinfo107405* info, NimStringDesc* f);
N_NIMCALL(void, parsetoken_109460)(Timeinfo107405* info, NimStringDesc* token, NimStringDesc* value, NI* j);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, nsuToLowerStr)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_NIMCALL(NimStringDesc*, nimCharToStr)(NIM_CHAR x);
N_NIMCALL(NimStringDesc*, nsuToUpperStr)(NimStringDesc* s);
N_NIMCALL(void, parse_110352)(NimStringDesc* value, NimStringDesc* layout, Timeinfo107405* Result);
STRING_LITERAL(TMP158, "UTC", 3);
NIM_CONST TY108054 weekdays_108053 = {((NU8) 6),
((NU8) 0),
((NU8) 1),
((NU8) 2),
((NU8) 3),
((NU8) 4),
((NU8) 5)}
;
NIM_CONST TY108073 weekdays_108072 = {((NI8) 1),
((NI8) 2),
((NI8) 3),
((NI8) 4),
((NI8) 5),
((NI8) 6),
((NI8) 0)}
;
STRING_LITERAL(TMP159, "", 0);
STRING_LITERAL(TMP163, "Monday", 6);
STRING_LITERAL(TMP164, "Tuesday", 7);
STRING_LITERAL(TMP165, "Wednesday", 9);
STRING_LITERAL(TMP166, "Thursday", 8);
STRING_LITERAL(TMP167, "Friday", 6);
STRING_LITERAL(TMP168, "Saturday", 8);
STRING_LITERAL(TMP169, "Sunday", 6);
NIM_CONST TY109239 lookup_109238 = {((NimStringDesc*) &TMP163),
((NimStringDesc*) &TMP164),
((NimStringDesc*) &TMP165),
((NimStringDesc*) &TMP166),
((NimStringDesc*) &TMP167),
((NimStringDesc*) &TMP168),
((NimStringDesc*) &TMP169)}
;
STRING_LITERAL(TMP170, "January", 7);
STRING_LITERAL(TMP171, "February", 8);
STRING_LITERAL(TMP172, "March", 5);
STRING_LITERAL(TMP173, "April", 5);
STRING_LITERAL(TMP174, "May", 3);
STRING_LITERAL(TMP175, "June", 4);
STRING_LITERAL(TMP176, "July", 4);
STRING_LITERAL(TMP177, "August", 6);
STRING_LITERAL(TMP178, "September", 9);
STRING_LITERAL(TMP179, "October", 7);
STRING_LITERAL(TMP180, "November", 8);
STRING_LITERAL(TMP181, "December", 8);
NIM_CONST TY109255 lookup_109254 = {((NimStringDesc*) &TMP170),
((NimStringDesc*) &TMP171),
((NimStringDesc*) &TMP172),
((NimStringDesc*) &TMP173),
((NimStringDesc*) &TMP174),
((NimStringDesc*) &TMP175),
((NimStringDesc*) &TMP176),
((NimStringDesc*) &TMP177),
((NimStringDesc*) &TMP178),
((NimStringDesc*) &TMP179),
((NimStringDesc*) &TMP180),
((NimStringDesc*) &TMP181)}
;
STRING_LITERAL(TMP182, "d", 1);
STRING_LITERAL(TMP183, "dd", 2);
STRING_LITERAL(TMP184, "ddd", 3);
STRING_LITERAL(TMP185, "dddd", 4);
STRING_LITERAL(TMP186, "h", 1);
STRING_LITERAL(TMP187, "hh", 2);
STRING_LITERAL(TMP188, "H", 1);
STRING_LITERAL(TMP189, "HH", 2);
STRING_LITERAL(TMP190, "m", 1);
STRING_LITERAL(TMP191, "mm", 2);
STRING_LITERAL(TMP192, "M", 1);
STRING_LITERAL(TMP193, "MM", 2);
STRING_LITERAL(TMP194, "MMM", 3);
STRING_LITERAL(TMP195, "MMMM", 4);
STRING_LITERAL(TMP196, "s", 1);
STRING_LITERAL(TMP197, "ss", 2);
STRING_LITERAL(TMP198, "t", 1);
STRING_LITERAL(TMP199, "tt", 2);
STRING_LITERAL(TMP200, "y", 1);
STRING_LITERAL(TMP201, "yy", 2);
STRING_LITERAL(TMP202, "yyy", 3);
STRING_LITERAL(TMP203, "yyyy", 4);
STRING_LITERAL(TMP204, "yyyyy", 5);
STRING_LITERAL(TMP205, "z", 1);
STRING_LITERAL(TMP206, "zz", 2);
STRING_LITERAL(TMP207, "zzz", 3);
STRING_LITERAL(TMP208, "ZZZ", 3);
STRING_LITERAL(TMP209, "0", 1);
STRING_LITERAL(TMP210, "PM", 2);
STRING_LITERAL(TMP211, "AM", 2);
STRING_LITERAL(TMP212, ":00", 3);
STRING_LITERAL(TMP213, "Invalid format string: ", 23);
STRING_LITERAL(TMP225, "sun", 3);
STRING_LITERAL(TMP226, "mon", 3);
STRING_LITERAL(TMP227, "tue", 3);
STRING_LITERAL(TMP228, "wed", 3);
STRING_LITERAL(TMP229, "thu", 3);
STRING_LITERAL(TMP230, "fri", 3);
STRING_LITERAL(TMP231, "sat", 3);
STRING_LITERAL(TMP232, "invalid day of week ", 20);
STRING_LITERAL(TMP233, "sunday", 6);
STRING_LITERAL(TMP234, "monday", 6);
STRING_LITERAL(TMP235, "tuesday", 7);
STRING_LITERAL(TMP236, "wednesday", 9);
STRING_LITERAL(TMP237, "thursday", 8);
STRING_LITERAL(TMP238, "friday", 6);
STRING_LITERAL(TMP239, "saturday", 8);
STRING_LITERAL(TMP240, "jan", 3);
STRING_LITERAL(TMP241, "feb", 3);
STRING_LITERAL(TMP242, "mar", 3);
STRING_LITERAL(TMP243, "apr", 3);
STRING_LITERAL(TMP244, "may", 3);
STRING_LITERAL(TMP245, "jun", 3);
STRING_LITERAL(TMP246, "jul", 3);
STRING_LITERAL(TMP247, "aug", 3);
STRING_LITERAL(TMP248, "sep", 3);
STRING_LITERAL(TMP249, "oct", 3);
STRING_LITERAL(TMP250, "nov", 3);
STRING_LITERAL(TMP251, "dec", 3);
STRING_LITERAL(TMP252, "invalid month", 13);
STRING_LITERAL(TMP253, "january", 7);
STRING_LITERAL(TMP254, "february", 8);
STRING_LITERAL(TMP255, "march", 5);
STRING_LITERAL(TMP256, "april", 5);
STRING_LITERAL(TMP257, "june", 4);
STRING_LITERAL(TMP258, "july", 4);
STRING_LITERAL(TMP259, "august", 6);
STRING_LITERAL(TMP260, "september", 9);
STRING_LITERAL(TMP261, "october", 7);
STRING_LITERAL(TMP262, "november", 8);
STRING_LITERAL(TMP263, "december", 8);
STRING_LITERAL(TMP264, "Sign for timezone ", 18);
extern TFrame* frameptr_17042;
extern TNimType NTI3411; /* RootObj */
TNimType NTI107405; /* TimeInfo */
extern TNimType NTI108; /* int */
TNimType NTI107408; /* range 0..61(int) */
TNimType NTI107410; /* range 0..59(int) */
TNimType NTI107412; /* range 0..23(int) */
TNimType NTI107415; /* range 1..31(int) */
TNimType NTI104006; /* Month */
TNimType NTI107418; /* range -10000..10000(int) */
TNimType NTI104008; /* WeekDay */
TNimType NTI107424; /* range 0..365(int) */
extern TNimType NTI138; /* bool */
extern TNimType NTI149; /* string */
extern TY105625 Dl_105624;
extern TNimType NTI22801; /* ref ValueError */
extern TNimType NTI3449; /* ValueError */
extern Tgcheap48616 gch_48644;

N_NIMCALL(time_t, fromseconds_107477)(NI64 since1970) {
	time_t result;
	result = 0;
	result = fromseconds_107471(((NF) (since1970)));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLtTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 < IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntLeTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 <= IL64(0));
	return result;
}

N_NIMCALL(NIM_BOOL, ntEqTime)(time_t a, time_t b) {
	NIM_BOOL result;
	NI64 LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ntDiffTime(a, b);
	result = (LOC1 == IL64(0));
	return result;
}

N_NIMCALL(Timeinterval107407, initinterval_107614)(NI miliseconds, NI seconds, NI minutes, NI hours, NI days, NI months, NI years) {
	Timeinterval107407 result;
	memset((void*)(&result), 0, sizeof(result));
	result.miliseconds = miliseconds;
	result.seconds = seconds;
	result.minutes = minutes;
	result.hours = hours;
	result.days = days;
	result.months = months;
	result.years = years;
	return result;
}

N_NIMCALL(NIM_BOOL, isleapyear_107630)(NI year) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(((NI) ((NI)(year % ((NI) 400)))) == ((NI) 0))) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA3: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 100)))) == ((NI) 0))) goto LA6;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	goto LA1;
	LA6: ;
	{
		if (!(((NI) ((NI)(year % ((NI) 4)))) == ((NI) 0))) goto LA9;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	goto LA1;
	LA9: ;
	{
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getdaysinmonth_107645)(NU8 month, NI year) {
	NI result;
	result = 0;
	switch (month) {
	case ((NU8) 1):
	{
		{
			NIM_BOOL LOC4;
			LOC4 = 0;
			LOC4 = isleapyear_107630(year);
			if (!LOC4) goto LA5;
			result = ((NI) 29);
		}
		goto LA2;
		LA5: ;
		{
			result = ((NI) 28);
		}
		LA2: ;
	}
	break;
	case ((NU8) 3):
	case ((NU8) 5):
	case ((NU8) 8):
	case ((NU8) 10):
	{
		result = ((NI) 30);
	}
	break;
	default:
	{
		result = ((NI) 31);
	}
	break;
	}
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

static N_INLINE(void, HEX2BHEX3D_107689)(NF* x, NF y) {
	nimfr("+=", "system.nim")
	nimln(2992, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(NF, HEX2F_87999)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2856, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(NF, toseconds_107658)(Timeinfo107405* a, Timeinterval107407* interval) {
	NF result;
	Timeinfo107405 anew;
	Timeinterval107407 newinterv;
	NU8 curmonth;
	NF LOC10;
	result = 0;
	memset((void*)(&anew), 0, sizeof(anew));
	anew.Sup.m_type = (&NTI107405);
	genericAssign((void*)(&anew), (void*)a, (&NTI107405));
	newinterv = (*interval);
	result = 0.0;
	newinterv.months += (NI)((*interval).years * ((NI) 12));
	curmonth = anew.month;
	{
		NI mth_107685;
		NI HEX3Atmp_107782;
		NI res_107785;
		mth_107685 = 0;
		HEX3Atmp_107782 = 0;
		HEX3Atmp_107782 = newinterv.months;
		res_107785 = ((NI) 1);
		{
			while (1) {
				NI LOC4;
				if (!(res_107785 <= HEX3Atmp_107782)) goto LA3;
				mth_107685 = res_107785;
				LOC4 = 0;
				LOC4 = getdaysinmonth_107645(curmonth, ((NI) (anew.year)));
				HEX2BHEX3D_107689((&result), ((NF) ((NI)((NI)((NI)(LOC4 * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
				{
					if (!(curmonth == ((NU8) 11))) goto LA7;
					curmonth = ((NU8) 0);
					anew.year += ((NI) 1);
				}
				goto LA5;
				LA7: ;
				{
					curmonth += ((NI) 1);
				}
				LA5: ;
				res_107785 += ((NI) 1);
			} LA3: ;
		}
	}
	HEX2BHEX3D_107689((&result), ((NF) ((NI)((NI)((NI)(newinterv.days * ((NI) 24)) * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_107689((&result), ((NF) ((NI)((NI)(newinterv.hours * ((NI) 60)) * ((NI) 60)))));
	HEX2BHEX3D_107689((&result), ((NF) ((NI)(newinterv.minutes * ((NI) 60)))));
	HEX2BHEX3D_107689((&result), ((NF) (newinterv.seconds)));
	LOC10 = 0;
	LOC10 = HEX2F_87999(newinterv.miliseconds, ((NI) 1000));
	HEX2BHEX3D_107689((&result), LOC10);
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL LOC11;
	int LOC13;
{	result = 0;
	{
		if (!(a == b)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == NIM_NIL);
		if (LOC7) goto LA8;
		LOC7 = (b == NIM_NIL);
		LA8: ;
		if (!LOC7) goto LA9;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA9: ;
	LOC11 = 0;
	LOC11 = ((*a).Sup.len == (*b).Sup.len);
	if (!(LOC11)) goto LA12;
	LOC13 = 0;
	LOC13 = memcmp(((NCSTRING) ((*a).data)), ((NCSTRING) ((*b).data)), (*a).Sup.len);
	LOC11 = (LOC13 == ((NI32) 0));
	LA12: ;
	result = LOC11;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, HEX2B_107808)(Timeinfo107405* a, Timeinterval107407* interval, Timeinfo107405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_107465(a);
	t = toseconds_107488(LOC1);
	secs = toseconds_107658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).tzname, ((NimStringDesc*) &TMP158))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_107471(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getgmtime_107459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_107471(((NF)(t) + (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getlocaltime_107453(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, HEX2D_107821)(Timeinfo107405* a, Timeinterval107407* interval, Timeinfo107405* Result) {
	NF t;
	time_t LOC1;
	NF secs;
	LOC1 = 0;
	LOC1 = timeinfototime_107465(a);
	t = toseconds_107488(LOC1);
	secs = toseconds_107658(a, interval);
	{
		time_t LOC6;
		if (!eqStrings((*a).tzname, ((NimStringDesc*) &TMP158))) goto LA4;
		LOC6 = 0;
		LOC6 = fromseconds_107471(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getgmtime_107459(LOC6, Result);
	}
	goto LA2;
	LA4: ;
	{
		time_t LOC8;
		LOC8 = 0;
		LOC8 = fromseconds_107471(((NF)(t) - (NF)(secs)));
		genericReset((void*)Result, (&NTI107405));
		(*Result).Sup.m_type = (&NTI107405);
		getlocaltime_107453(LOC8, Result);
	}
	LA2: ;
}

N_NIMCALL(void, gettzname_107546)(TY107548* Result) {
{	unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(tzname[(((NI) 0))- 0]));
	unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(tzname[(((NI) 1))- 0]));
	goto BeforeRet;
	}BeforeRet: ;
}

N_NIMCALL(NI, gettimezone_107604)(void) {
	NI result;
{	result = 0;
	result = timezone;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, tmtotimeinfo_108048)(struct tm* tm, NIM_BOOL local, Timeinfo107405* Result) {
	Timeinfo107405 LOC1;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107405);
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Sup.m_type = (&NTI107405);
	LOC1.second = ((NI) (((NI) ((*tm).tm_sec))));
	LOC1.minute = ((NI) (((NI) ((*tm).tm_min))));
	LOC1.hour = ((NI) (((NI) ((*tm).tm_hour))));
	LOC1.monthday = ((NI) (((NI) ((*tm).tm_mday))));
	LOC1.month = ((NU8) ((*tm).tm_mon));
	LOC1.year = ((NI) ((NI32)((*tm).tm_year + ((NI32) 1900))));
	LOC1.weekday = weekdays_108053[(((NI) ((*tm).tm_wday)))- 0];
	LOC1.yearday = ((NI) (((NI) ((*tm).tm_yday))));
	LOC1.isdst = (((NI32) 0) < (*tm).tm_isdst);
	{
		if (!local) goto LA4;
		{
			TY107548 LOC10;
			if (!(((NI32) 0) < (*tm).tm_isdst)) goto LA8;
			memset((void*)(&LOC10), 0, sizeof(LOC10));
			gettzname_107546((&LOC10));
			LOC1.tzname = copyString(LOC10.Field1);
		}
		goto LA6;
		LA8: ;
		{
			TY107548 LOC12;
			memset((void*)(&LOC12), 0, sizeof(LOC12));
			gettzname_107546((&LOC12));
			LOC1.tzname = copyString(LOC12.Field0);
		}
		LA6: ;
	}
	goto LA2;
	LA4: ;
	{
		LOC1.tzname = copyString(((NimStringDesc*) &TMP158));
	}
	LA2: ;
	{
		if (!local) goto LA16;
		LOC1.timezone = gettimezone_107604();
	}
	goto LA14;
	LA16: ;
	{
		LOC1.timezone = ((NI) 0);
	}
	LA14: ;
	genericShallowAssign((void*)Result, (void*)(&LOC1), (&NTI107405));
}

N_NIMCALL(struct tm, timeinfototm_108068)(Timeinfo107405* t) {
	struct tm result;
	NI LOC1;
	memset((void*)(&result), 0, sizeof(result));
	result.tm_sec = ((int) ((*t).second));
	result.tm_min = ((int) ((*t).minute));
	result.tm_hour = ((int) ((*t).hour));
	result.tm_mday = ((int) ((*t).monthday));
	result.tm_mon = ((int) ((*t).month));
	result.tm_year = ((int) ((NI)(((NI) ((*t).year)) - ((NI) 1900))));
	result.tm_wday = ((int) (weekdays_108072[((*t).weekday)- 0]));
	result.tm_yday = ((int) ((*t).yearday));
	LOC1 = 0;
	{
		if (!(*t).isdst) goto LA4;
		LOC1 = ((NI) 1);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) 0);
	}
	LA2: ;
	result.tm_isdst = ((int) (LOC1));
	return result;
}

N_NIMCALL(NI64, ntDiffTime)(time_t a, time_t b) {
	NI64 result;
	NF LOC1;
{	result = 0;
	LOC1 = 0;
	LOC1 = difftime(a, b);
	result = float64ToInt64(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getstartmilsecs_107609)(void) {
	NI result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = (NI)(LOC1 / (NI)(CLOCKS_PER_SEC / ((NI) 1000)));
	return result;
}

N_NIMCALL(time_t, gettime_107448)(void) {
	time_t result;
{	result = 0;
	result = time(NIM_NIL);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getlocaltime_107453)(time_t t, Timeinfo107405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = localtime((&a));
	genericReset((void*)Result, (&NTI107405));
	(*Result).Sup.m_type = (&NTI107405);
	tmtotimeinfo_108048((&(*LOC1)), NIM_TRUE, Result);
}

N_NIMCALL(void, getgmtime_107459)(time_t t, Timeinfo107405* Result) {
	time_t a;
	struct tm* LOC1;
	a = t;
	LOC1 = 0;
	LOC1 = gmtime((&a));
	genericReset((void*)Result, (&NTI107405));
	(*Result).Sup.m_type = (&NTI107405);
	tmtotimeinfo_108048((&(*LOC1)), NIM_FALSE, Result);
}

N_NIMCALL(time_t, timeinfototime_107465)(Timeinfo107405* timeinfo) {
	time_t result;
	Timeinfo107405 ctimeinfo;
	struct tm LOC1;
{	result = 0;
	memset((void*)(&ctimeinfo), 0, sizeof(ctimeinfo));
	ctimeinfo.Sup.m_type = (&NTI107405);
	genericAssign((void*)(&ctimeinfo), (void*)timeinfo, (&NTI107405));
	LOC1 = timeinfototm_108068((&ctimeinfo));
	result = mktime((&LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, tostringtillnl_108637)(NCSTRING p) {
	NimStringDesc* result;
	NI i;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP159));
	i = ((NI) 0);
	{
		while (1) {
			NIM_BOOL LOC3;
			NIM_BOOL LOC4;
			LOC3 = 0;
			LOC4 = 0;
			LOC4 = !(((NU8)(p[i]) == (NU8)(0)));
			if (!(LOC4)) goto LA5;
			LOC4 = !(((NU8)(p[i]) == (NU8)(10)));
			LA5: ;
			LOC3 = LOC4;
			if (!(LOC3)) goto LA6;
			LOC3 = !(((NU8)(p[i]) == (NU8)(13)));
			LA6: ;
			if (!LOC3) goto LA2;
			result = addChar(result, p[i]);
			i += ((NI) 1);
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107494)(Timeinfo107405* timeinfo) {
	NimStringDesc* result;
	NCSTRING p;
	struct tm LOC1;
	result = 0;
	LOC1 = timeinfototm_108068(timeinfo);
	p = asctime((&LOC1));
	result = tostringtillnl_108637(p);
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_107500)(time_t time) {
	NimStringDesc* result;
	time_t a;
	NCSTRING LOC1;
{	result = 0;
	a = time;
	LOC1 = 0;
	LOC1 = ctime((&a));
	result = tostringtillnl_108637(LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI64, unixtimetowintime_108680)(time_t t) {
	NI64 result;
	result = 0;
	result = (NI64)((NI64)(((NI64) (t)) * IL64(10000000)) + IL64(116444736000000000));
	return result;
}

N_NIMCALL(time_t, wintimetounixtime_108688)(NI64 t) {
	time_t result;
	result = 0;
	result = ((time_t) ((NI64)((NI64)(t - IL64(116444736000000000)) / IL64(10000000))));
	return result;
}

N_NIMCALL(time_t, fromseconds_107471)(NF since1970) {
	time_t result;
	result = 0;
	result = ((time_t) (since1970));
	return result;
}

N_NIMCALL(NF, toseconds_107488)(time_t time) {
	NF result;
	result = 0;
	result = ((NF) (time));
	return result;
}

N_NIMCALL(NF, ntepochTime)(void) {
	NF result;
	Tfiletime104245 f;
	NI64 i64;
	NI64 LOC1;
	NI64 secs;
	NI64 subsecs;
	result = 0;
	memset((void*)(&f), 0, sizeof(f));
	Dl_105624((&f));
	LOC1 = 0;
	LOC1 = rdfiletime_105604(f);
	i64 = (NI64)(LOC1 - IL64(116444736000000000));
	secs = (NI64)(i64 / IL64(10000000));
	subsecs = (NI64)(i64 % IL64(10000000));
	result = ((NF)(((double) (((NI) (secs))))) + (NF)(((NF)(((double) (((NI) (subsecs))))) * (NF)(9.9999999999999995e-008))));
	return result;
}

N_NIMCALL(NF, ntcpuTime)(void) {
	NF result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = clock();
	result = ((NF)(((double) (LOC1))) / (NF)(((double) (CLOCKS_PER_SEC))));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, ntgetDateStr)(void) {
	NimStringDesc* result;
	Timeinfo107405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	LOC1 = 0;
	LOC1 = gettime_107448();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nimIntToStr(((NI) (ti.year)));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) ((NI)(((NI) (ti.month)) + ((NI) 1)))), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.monthday)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 45);
appendString(LOC2, LOC4);
appendChar(LOC2, 45);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, ntgetClockStr)(void) {
	NimStringDesc* result;
	Timeinfo107405 ti;
	time_t LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	NimStringDesc* LOC4;
	NimStringDesc* LOC5;
	result = 0;
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	LOC1 = 0;
	LOC1 = gettime_107448();
	memset((void*)(&ti), 0, sizeof(ti));
	ti.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC1, (&ti));
	LOC2 = 0;
	LOC3 = 0;
	LOC3 = nsuIntToStr(((NI) (ti.hour)), ((NI) 2));
	LOC4 = 0;
	LOC4 = nsuIntToStr(((NI) (ti.minute)), ((NI) 2));
	LOC5 = 0;
	LOC5 = nsuIntToStr(((NI) (ti.second)), ((NI) 2));
	LOC2 = rawNewString(LOC3->Sup.len + LOC4->Sup.len + LOC5->Sup.len + 2);
appendString(LOC2, LOC3);
appendChar(LOC2, 58);
appendString(LOC2, LOC4);
appendChar(LOC2, 58);
appendString(LOC2, LOC5);
	result = LOC2;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_109234)(NU8 day) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_109238[(day)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_109250)(NU8 m) {
	NimStringDesc* result;
{	result = 0;
	result = copyString(lookup_109254[(m)- 0]);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NimStringDesc*, HEX5BHEX5D_88054)(NimStringDesc* s, Slice88061 x) {
	NimStringDesc* result;
	nimfr("[]", "system.nim")
	result = 0;
	nimln(2880, "system.nim");
	result = copyStrLast(s, x.a, x.b);
	popFrame();
	return result;
}

static N_INLINE(Slice88061, HEX2EHEX2E_109273)(NI a, NI b) {
	Slice88061 result;
	nimfr("..", "system.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(234, "system.nim");
	result.a = a;
	nimln(235, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

static N_INLINE(Tcell46746*, usrtocell_50246)(void* usr) {
	Tcell46746* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46746*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46746))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51804)(Tcell46746* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50217((&gch_48644.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		Tcell46746* c;
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(252, "gc.nim");
		c = usrtocell_50246(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		Tcell46746* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(255, "gc.nim");
		c = usrtocell_50246((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(257, "gc.nim");
			rtladdzct_51804(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, formattoken_109266)(Timeinfo107405* info, NimStringDesc* token, NimStringDesc** buf) {
	switch (hashString(token) & 31) {
	case 0: 
if (eqStrings(token, ((NimStringDesc*) &TMP159))) goto LA28;
break;
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP191))) goto LA10;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP182))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA18;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA27;
break;
	case 8: 
if (eqStrings(token, ((NimStringDesc*) &TMP200))) goto LA19;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP186))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA11;
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA12;
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA16;
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA20;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA13;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA26;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP185))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA17;
break;
	case 20: 
if (eqStrings(token, ((NimStringDesc*) &TMP204))) goto LA23;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP183))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP190))) goto LA9;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA15;
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA25;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP188))) goto LA7;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP189))) goto LA8;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA14;
break;
	case 29: 
if (eqStrings(token, ((NimStringDesc*) &TMP202))) goto LA21;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP205))) goto LA24;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP184))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP187))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA22;
break;
	}
	goto LA29;
	LA1: ;
	{
		NimStringDesc* LOC32;
		LOC32 = 0;
		LOC32 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC32->Sup.len + 0);
appendString((*buf), LOC32);
	}
	goto LA30;
	LA2: ;
	{
		NimStringDesc* LOC38;
		{
			if (!(((NI) ((*info).monthday)) < ((NI) 10))) goto LA36;
			(*buf) = resizeString((*buf), 1);
appendString((*buf), ((NimStringDesc*) &TMP209));
		}
		LA36: ;
		LOC38 = 0;
		LOC38 = nimIntToStr(((NI) ((*info).monthday)));
		(*buf) = resizeString((*buf), LOC38->Sup.len + 0);
appendString((*buf), LOC38);
	}
	goto LA30;
	LA3: ;
	{
		NimStringDesc* LOC40;
		Slice88061 LOC41;
		NimStringDesc* LOC42;
		LOC40 = 0;
		LOC40 = HEX24_109234((*info).weekday);
		LOC41 = HEX2EHEX2E_109273(((NI) 0), ((NI) 2));
		LOC42 = 0;
		LOC42 = HEX5BHEX5D_88054(LOC40, LOC41);
		(*buf) = resizeString((*buf), LOC42->Sup.len + 0);
appendString((*buf), LOC42);
	}
	goto LA30;
	LA4: ;
	{
		NimStringDesc* LOC44;
		LOC44 = 0;
		LOC44 = HEX24_109234((*info).weekday);
		(*buf) = resizeString((*buf), LOC44->Sup.len + 0);
appendString((*buf), LOC44);
	}
	goto LA30;
	LA5: ;
	{
		NI LOC46;
		NimStringDesc* LOC52;
		LOC46 = 0;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA49;
			LOC46 = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA47;
		LA49: ;
		{
			LOC46 = ((NI) ((*info).hour));
		}
		LA47: ;
		LOC52 = 0;
		LOC52 = nimIntToStr(LOC46);
		(*buf) = resizeString((*buf), LOC52->Sup.len + 0);
appendString((*buf), LOC52);
	}
	goto LA30;
	LA6: ;
	{
		NI amerhour;
		NimStringDesc* LOC63;
		{
			if (!(((NI) 12) < ((NI) ((*info).hour)))) goto LA56;
			amerhour = ((NI) ((NI)(((NI) ((*info).hour)) - ((NI) 12))));
		}
		goto LA54;
		LA56: ;
		{
			amerhour = ((NI) ((*info).hour));
		}
		LA54: ;
		{
			if (!(amerhour < ((NI) 10))) goto LA61;
			(*buf) = addChar((*buf), 48);
		}
		LA61: ;
		LOC63 = 0;
		LOC63 = nimIntToStr(amerhour);
		(*buf) = resizeString((*buf), LOC63->Sup.len + 0);
appendString((*buf), LOC63);
	}
	goto LA30;
	LA7: ;
	{
		NimStringDesc* LOC65;
		LOC65 = 0;
		LOC65 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC65->Sup.len + 0);
appendString((*buf), LOC65);
	}
	goto LA30;
	LA8: ;
	{
		NimStringDesc* LOC71;
		{
			if (!(((NI) ((*info).hour)) < ((NI) 10))) goto LA69;
			(*buf) = addChar((*buf), 48);
		}
		LA69: ;
		LOC71 = 0;
		LOC71 = nimIntToStr(((NI) ((*info).hour)));
		(*buf) = resizeString((*buf), LOC71->Sup.len + 0);
appendString((*buf), LOC71);
	}
	goto LA30;
	LA9: ;
	{
		NimStringDesc* LOC73;
		LOC73 = 0;
		LOC73 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC73->Sup.len + 0);
appendString((*buf), LOC73);
	}
	goto LA30;
	LA10: ;
	{
		NimStringDesc* LOC79;
		{
			if (!(((NI) ((*info).minute)) < ((NI) 10))) goto LA77;
			(*buf) = addChar((*buf), 48);
		}
		LA77: ;
		LOC79 = 0;
		LOC79 = nimIntToStr(((NI) ((*info).minute)));
		(*buf) = resizeString((*buf), LOC79->Sup.len + 0);
appendString((*buf), LOC79);
	}
	goto LA30;
	LA11: ;
	{
		NimStringDesc* LOC81;
		LOC81 = 0;
		LOC81 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC81->Sup.len + 0);
appendString((*buf), LOC81);
	}
	goto LA30;
	LA12: ;
	{
		NimStringDesc* LOC87;
		{
			if (!((*info).month < ((NU8) 9))) goto LA85;
			(*buf) = addChar((*buf), 48);
		}
		LA85: ;
		LOC87 = 0;
		LOC87 = nimIntToStr((NI)(((NI) ((*info).month)) + ((NI) 1)));
		(*buf) = resizeString((*buf), LOC87->Sup.len + 0);
appendString((*buf), LOC87);
	}
	goto LA30;
	LA13: ;
	{
		NimStringDesc* LOC89;
		Slice88061 LOC90;
		NimStringDesc* LOC91;
		LOC89 = 0;
		LOC89 = HEX24_109250((*info).month);
		LOC90 = HEX2EHEX2E_109273(((NI) 0), ((NI) 2));
		LOC91 = 0;
		LOC91 = HEX5BHEX5D_88054(LOC89, LOC90);
		(*buf) = resizeString((*buf), LOC91->Sup.len + 0);
appendString((*buf), LOC91);
	}
	goto LA30;
	LA14: ;
	{
		NimStringDesc* LOC93;
		LOC93 = 0;
		LOC93 = HEX24_109250((*info).month);
		(*buf) = resizeString((*buf), LOC93->Sup.len + 0);
appendString((*buf), LOC93);
	}
	goto LA30;
	LA15: ;
	{
		NimStringDesc* LOC95;
		LOC95 = 0;
		LOC95 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC95->Sup.len + 0);
appendString((*buf), LOC95);
	}
	goto LA30;
	LA16: ;
	{
		NimStringDesc* LOC101;
		{
			if (!(((NI) ((*info).second)) < ((NI) 10))) goto LA99;
			(*buf) = addChar((*buf), 48);
		}
		LA99: ;
		LOC101 = 0;
		LOC101 = nimIntToStr(((NI) ((*info).second)));
		(*buf) = resizeString((*buf), LOC101->Sup.len + 0);
appendString((*buf), LOC101);
	}
	goto LA30;
	LA17: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA105;
			(*buf) = addChar((*buf), 80);
		}
		goto LA103;
		LA105: ;
		{
			(*buf) = addChar((*buf), 65);
		}
		LA103: ;
	}
	goto LA30;
	LA18: ;
	{
		{
			if (!(((NI) 12) <= ((NI) ((*info).hour)))) goto LA111;
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP210));
		}
		goto LA109;
		LA111: ;
		{
			(*buf) = resizeString((*buf), 2);
appendString((*buf), ((NimStringDesc*) &TMP211));
		}
		LA109: ;
	}
	goto LA30;
	LA19: ;
	{
		NI fr;
		NimStringDesc* LOC115;
		NimStringDesc* LOC120;
		NimStringDesc* LOC121;
		Slice88061 LOC122;
		NimStringDesc* LOC123;
		LOC115 = 0;
		LOC115 = nimIntToStr(((NI) ((*info).year)));
		fr = (NI)((LOC115 ? LOC115->Sup.len : 0) - ((NI) 1));
		{
			if (!(fr < ((NI) 0))) goto LA118;
			fr = ((NI) 0);
		}
		LA118: ;
		LOC120 = 0;
		LOC120 = nimIntToStr(((NI) ((*info).year)));
		LOC121 = 0;
		LOC121 = nimIntToStr(((NI) ((*info).year)));
		LOC122 = HEX2EHEX2E_109273(fr, (NI)((LOC121 ? LOC121->Sup.len : 0) - ((NI) 1)));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_88054(LOC120, LOC122);
		(*buf) = resizeString((*buf), LOC123->Sup.len + 0);
appendString((*buf), LOC123);
	}
	goto LA30;
	LA20: ;
	{
		NI fr;
		NimStringDesc* LOC125;
		NimStringDesc* fyear;
		NimStringDesc* LOC130;
		NimStringDesc* LOC131;
		Slice88061 LOC132;
		LOC125 = 0;
		LOC125 = nimIntToStr(((NI) ((*info).year)));
		fr = (NI)((LOC125 ? LOC125->Sup.len : 0) - ((NI) 2));
		{
			if (!(fr < ((NI) 0))) goto LA128;
			fr = ((NI) 0);
		}
		LA128: ;
		LOC130 = 0;
		LOC130 = nimIntToStr(((NI) ((*info).year)));
		LOC131 = 0;
		LOC131 = nimIntToStr(((NI) ((*info).year)));
		LOC132 = HEX2EHEX2E_109273(fr, (NI)((LOC131 ? LOC131->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88054(LOC130, LOC132);
		{
			NimStringDesc* LOC137;
			NimStringDesc* LOC138;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 2)))) goto LA135;
			LOC137 = 0;
			LOC138 = 0;
			LOC138 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 2) - (fyear ? fyear->Sup.len : 0)))));
			LOC137 = rawNewString(LOC138->Sup.len + fyear->Sup.len + 0);
appendString(LOC137, LOC138);
appendString(LOC137, fyear);
			fyear = LOC137;
		}
		LA135: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA21: ;
	{
		NI fr;
		NimStringDesc* LOC140;
		NimStringDesc* fyear;
		NimStringDesc* LOC145;
		NimStringDesc* LOC146;
		Slice88061 LOC147;
		LOC140 = 0;
		LOC140 = nimIntToStr(((NI) ((*info).year)));
		fr = (NI)((LOC140 ? LOC140->Sup.len : 0) - ((NI) 3));
		{
			if (!(fr < ((NI) 0))) goto LA143;
			fr = ((NI) 0);
		}
		LA143: ;
		LOC145 = 0;
		LOC145 = nimIntToStr(((NI) ((*info).year)));
		LOC146 = 0;
		LOC146 = nimIntToStr(((NI) ((*info).year)));
		LOC147 = HEX2EHEX2E_109273(fr, (NI)((LOC146 ? LOC146->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88054(LOC145, LOC147);
		{
			NimStringDesc* LOC152;
			NimStringDesc* LOC153;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 3)))) goto LA150;
			LOC152 = 0;
			LOC153 = 0;
			LOC153 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 3) - (fyear ? fyear->Sup.len : 0)))));
			LOC152 = rawNewString(LOC153->Sup.len + fyear->Sup.len + 0);
appendString(LOC152, LOC153);
appendString(LOC152, fyear);
			fyear = LOC152;
		}
		LA150: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA22: ;
	{
		NI fr;
		NimStringDesc* LOC155;
		NimStringDesc* fyear;
		NimStringDesc* LOC160;
		NimStringDesc* LOC161;
		Slice88061 LOC162;
		LOC155 = 0;
		LOC155 = nimIntToStr(((NI) ((*info).year)));
		fr = (NI)((LOC155 ? LOC155->Sup.len : 0) - ((NI) 4));
		{
			if (!(fr < ((NI) 0))) goto LA158;
			fr = ((NI) 0);
		}
		LA158: ;
		LOC160 = 0;
		LOC160 = nimIntToStr(((NI) ((*info).year)));
		LOC161 = 0;
		LOC161 = nimIntToStr(((NI) ((*info).year)));
		LOC162 = HEX2EHEX2E_109273(fr, (NI)((LOC161 ? LOC161->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88054(LOC160, LOC162);
		{
			NimStringDesc* LOC167;
			NimStringDesc* LOC168;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 4)))) goto LA165;
			LOC167 = 0;
			LOC168 = 0;
			LOC168 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 4) - (fyear ? fyear->Sup.len : 0)))));
			LOC167 = rawNewString(LOC168->Sup.len + fyear->Sup.len + 0);
appendString(LOC167, LOC168);
appendString(LOC167, fyear);
			fyear = LOC167;
		}
		LA165: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA23: ;
	{
		NI fr;
		NimStringDesc* LOC170;
		NimStringDesc* fyear;
		NimStringDesc* LOC175;
		NimStringDesc* LOC176;
		Slice88061 LOC177;
		LOC170 = 0;
		LOC170 = nimIntToStr(((NI) ((*info).year)));
		fr = (NI)((LOC170 ? LOC170->Sup.len : 0) - ((NI) 5));
		{
			if (!(fr < ((NI) 0))) goto LA173;
			fr = ((NI) 0);
		}
		LA173: ;
		LOC175 = 0;
		LOC175 = nimIntToStr(((NI) ((*info).year)));
		LOC176 = 0;
		LOC176 = nimIntToStr(((NI) ((*info).year)));
		LOC177 = HEX2EHEX2E_109273(fr, (NI)((LOC176 ? LOC176->Sup.len : 0) - ((NI) 1)));
		fyear = HEX5BHEX5D_88054(LOC175, LOC177);
		{
			NimStringDesc* LOC182;
			NimStringDesc* LOC183;
			if (!!(((fyear ? fyear->Sup.len : 0) == ((NI) 5)))) goto LA180;
			LOC182 = 0;
			LOC183 = 0;
			LOC183 = nsuRepeatChar(48, ((NI) ((NI)(((NI) 5) - (fyear ? fyear->Sup.len : 0)))));
			LOC182 = rawNewString(LOC183->Sup.len + fyear->Sup.len + 0);
appendString(LOC182, LOC183);
appendString(LOC182, fyear);
			fyear = LOC182;
		}
		LA180: ;
		(*buf) = resizeString((*buf), fyear->Sup.len + 0);
appendString((*buf), fyear);
	}
	goto LA30;
	LA24: ;
	{
		NI hrs;
		NimStringDesc* LOC185;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC185 = 0;
		LOC185 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC185->Sup.len + 0);
appendString((*buf), LOC185);
	}
	goto LA30;
	LA25: ;
	{
		NI hrs;
		NimStringDesc* LOC187;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC187 = 0;
		LOC187 = nimIntToStr(hrs);
		(*buf) = resizeString((*buf), LOC187->Sup.len + 0);
appendString((*buf), LOC187);
		{
			NI atindex;
			NimStringDesc* LOC192;
			NI LOC193;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA190;
			LOC192 = 0;
			LOC192 = nimIntToStr(hrs);
			LOC193 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA196;
				LOC193 = ((NI) 1);
			}
			goto LA194;
			LA196: ;
			{
				LOC193 = ((NI) 0);
			}
			LA194: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC192 ? LOC192->Sup.len : 0) - LOC193));
			insert_89801(buf, ((NimStringDesc*) &TMP209), ((NI) (atindex)));
		}
		LA190: ;
	}
	goto LA30;
	LA26: ;
	{
		NI hrs;
		NimStringDesc* LOC200;
		NimStringDesc* LOC201;
		hrs = (NI)((NI)((*info).timezone / ((NI) 60)) / ((NI) 60));
		LOC200 = 0;
		LOC201 = 0;
		LOC201 = nimIntToStr(hrs);
		LOC200 = rawNewString(LOC201->Sup.len + 3);
appendString(LOC200, LOC201);
appendString(LOC200, ((NimStringDesc*) &TMP212));
		(*buf) = resizeString((*buf), LOC200->Sup.len + 0);
appendString((*buf), LOC200);
		{
			NI atindex;
			NimStringDesc* LOC206;
			NimStringDesc* LOC207;
			NI LOC208;
			if (!((hrs > 0? (hrs) : -(hrs)) < ((NI) 10))) goto LA204;
			LOC206 = 0;
			LOC207 = 0;
			LOC207 = nimIntToStr(hrs);
			LOC206 = rawNewString(LOC207->Sup.len + 3);
appendString(LOC206, LOC207);
appendString(LOC206, ((NimStringDesc*) &TMP212));
			LOC208 = 0;
			{
				if (!(hrs < ((NI) 0))) goto LA211;
				LOC208 = ((NI) 1);
			}
			goto LA209;
			LA211: ;
			{
				LOC208 = ((NI) 0);
			}
			LA209: ;
			atindex = (NI)(((*buf) ? (*buf)->Sup.len : 0) - (NI)((LOC206 ? LOC206->Sup.len : 0) - LOC208));
			insert_89801(buf, ((NimStringDesc*) &TMP209), ((NI) (atindex)));
		}
		LA204: ;
	}
	goto LA30;
	LA27: ;
	{
		(*buf) = resizeString((*buf), (*info).tzname->Sup.len + 0);
appendString((*buf), (*info).tzname);
	}
	goto LA30;
	LA28: ;
	{
	}
	goto LA30;
	LA29: ;
	{
		Valueerror3449* e_109373;
		NimStringDesc* LOC217;
		e_109373 = 0;
		e_109373 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
		(*e_109373).Sup.Sup.m_type = (&NTI3449);
		LOC217 = 0;
		LOC217 = rawNewString(token->Sup.len + 23);
appendString(LOC217, ((NimStringDesc*) &TMP213));
appendString(LOC217, token);
		asgnRefNoCycle((void**) (&(*e_109373).Sup.message), LOC217);
		raiseException((Exception*)e_109373, "ValueError");
	}
	LA30: ;
}

N_NIMCALL(NimStringDesc*, format_109392)(Timeinfo107405* info, NimStringDesc* f) {
	NimStringDesc* result;
	NI i;
	NimStringDesc* currentf;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP159));
	i = ((NI) 0);
	currentf = copyString(((NimStringDesc*) &TMP159));
	{
		while (1) {
			switch (((NU8)(f->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				formattoken_109266(info, currentf, (&result));
				currentf = copyString(((NimStringDesc*) &TMP159));
				{
					if (!((NU8)(f->data[i]) == (NU8)(0))) goto LA6;
					goto LA1;
				}
				LA6: ;
				{
					if (!((NU8)(f->data[i]) == (NU8)(39))) goto LA10;
					i += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC14;
							LOC14 = 0;
							LOC14 = !(((NU8)(f->data[i]) == (NU8)(39)));
							if (!(LOC14)) goto LA15;
							LOC14 = (i < (NI)((f ? f->Sup.len : 0) - ((NI) 1)));
							LA15: ;
							if (!LOC14) goto LA13;
							result = addChar(result, f->data[i]);
							i += ((NI) 1);
						} LA13: ;
					}
				}
				goto LA8;
				LA10: ;
				{
					result = addChar(result, f->data[i]);
				}
				LA8: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC20;
					LOC20 = 0;
					LOC20 = ((currentf ? currentf->Sup.len : 0) < ((NI) 1));
					if (LOC20) goto LA21;
					LOC20 = ((NU8)(currentf->data[(currentf ? (currentf->Sup.len-1) : -1)]) == (NU8)(f->data[i]));
					LA21: ;
					if (!LOC20) goto LA22;
					currentf = addChar(currentf, f->data[i]);
				}
				goto LA18;
				LA22: ;
				{
					formattoken_109266(info, currentf, (&result));
					i -= ((NI) 1);
					currentf = copyString(((NimStringDesc*) &TMP159));
				}
				LA18: ;
			}
			break;
			}
			i += ((NI) 1);
		}
	} LA1: ;
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Tcell46746* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_50246(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_51804(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, parsetoken_109460)(Timeinfo107405* info, NimStringDesc* token, NimStringDesc* value, NI* j) {
	NI sv;
	sv = 0;
	switch (hashString(token) & 31) {
	case 1: 
if (eqStrings(token, ((NimStringDesc*) &TMP191))) goto LA8;
break;
	case 5: 
if (eqStrings(token, ((NimStringDesc*) &TMP182))) goto LA1;
break;
	case 6: 
if (eqStrings(token, ((NimStringDesc*) &TMP199))) goto LA16;
break;
	case 7: 
if (eqStrings(token, ((NimStringDesc*) &TMP208))) goto LA22;
break;
	case 10: 
if (eqStrings(token, ((NimStringDesc*) &TMP186))) goto LA5;
if (eqStrings(token, ((NimStringDesc*) &TMP192))) goto LA9;
if (eqStrings(token, ((NimStringDesc*) &TMP193))) goto LA10;
if (eqStrings(token, ((NimStringDesc*) &TMP197))) goto LA14;
if (eqStrings(token, ((NimStringDesc*) &TMP201))) goto LA17;
break;
	case 12: 
if (eqStrings(token, ((NimStringDesc*) &TMP194))) goto LA11;
break;
	case 14: 
if (eqStrings(token, ((NimStringDesc*) &TMP207))) goto LA21;
break;
	case 15: 
if (eqStrings(token, ((NimStringDesc*) &TMP185))) goto LA4;
if (eqStrings(token, ((NimStringDesc*) &TMP198))) goto LA15;
break;
	case 21: 
if (eqStrings(token, ((NimStringDesc*) &TMP183))) goto LA2;
if (eqStrings(token, ((NimStringDesc*) &TMP190))) goto LA7;
break;
	case 22: 
if (eqStrings(token, ((NimStringDesc*) &TMP196))) goto LA13;
if (eqStrings(token, ((NimStringDesc*) &TMP206))) goto LA20;
break;
	case 24: 
if (eqStrings(token, ((NimStringDesc*) &TMP188))) goto LA5;
break;
	case 25: 
if (eqStrings(token, ((NimStringDesc*) &TMP189))) goto LA6;
break;
	case 28: 
if (eqStrings(token, ((NimStringDesc*) &TMP195))) goto LA12;
break;
	case 30: 
if (eqStrings(token, ((NimStringDesc*) &TMP205))) goto LA19;
break;
	case 31: 
if (eqStrings(token, ((NimStringDesc*) &TMP184))) goto LA3;
if (eqStrings(token, ((NimStringDesc*) &TMP187))) goto LA6;
if (eqStrings(token, ((NimStringDesc*) &TMP203))) goto LA18;
break;
	}
	goto LA23;
	LA1: ;
	{
		NI pd;
		Slice88061 LOC26;
		NimStringDesc* LOC27;
		LOC26 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC27 = 0;
		LOC27 = HEX5BHEX5D_88054(value, LOC26);
		pd = npuParseInt(LOC27, (&sv), ((NI) 0));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA2: ;
	{
		Slice88061 LOC29;
		NimStringDesc* LOC30;
		NI LOC31;
		LOC29 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC30 = 0;
		LOC30 = HEX5BHEX5D_88054(value, LOC29);
		LOC31 = 0;
		LOC31 = nsuParseInt(LOC30);
		(*info).monthday = ((NI) (LOC31));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA3: ;
	{
		Slice88061 LOC33;
		NimStringDesc* LOC34;
		NimStringDesc* LOC35;
		LOC33 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 2)));
		LOC34 = 0;
		LOC34 = HEX5BHEX5D_88054(value, LOC33);
		LOC35 = 0;
		LOC35 = nsuToLowerStr(LOC34);
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP225))) goto LA36;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP226))) goto LA37;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP227))) goto LA38;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP228))) goto LA39;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP229))) goto LA40;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP230))) goto LA41;
		if (eqStrings(LOC35, ((NimStringDesc*) &TMP231))) goto LA42;
		goto LA43;
		LA36: ;
		{
			(*info).weekday = ((NU8) 6);
		}
		goto LA44;
		LA37: ;
		{
			(*info).weekday = ((NU8) 0);
		}
		goto LA44;
		LA38: ;
		{
			(*info).weekday = ((NU8) 1);
		}
		goto LA44;
		LA39: ;
		{
			(*info).weekday = ((NU8) 2);
		}
		goto LA44;
		LA40: ;
		{
			(*info).weekday = ((NU8) 3);
		}
		goto LA44;
		LA41: ;
		{
			(*info).weekday = ((NU8) 4);
		}
		goto LA44;
		LA42: ;
		{
			(*info).weekday = ((NU8) 5);
		}
		goto LA44;
		LA43: ;
		{
			Valueerror3449* e_109521;
			NimStringDesc* LOC53;
			e_109521 = 0;
			e_109521 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_109521).Sup.Sup.m_type = (&NTI3449);
			LOC53 = 0;
			LOC53 = (*e_109521).Sup.message; (*e_109521).Sup.message = copyStringRC1(((NimStringDesc*) &TMP232));
			if (LOC53) nimGCunrefNoCycle(LOC53);
			raiseException((Exception*)e_109521, "ValueError");
		}
		LA44: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA4: ;
	{
		{
			NIM_BOOL LOC57;
			Slice88061 LOC59;
			NimStringDesc* LOC60;
			NI LOC61;
			LOC57 = 0;
			LOC57 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC57)) goto LA58;
			LOC59 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 5)));
			LOC60 = 0;
			LOC60 = HEX5BHEX5D_88054(value, LOC59);
			LOC61 = 0;
			LOC61 = nsuCmpIgnoreCase(LOC60, ((NimStringDesc*) &TMP233));
			LOC57 = (LOC61 == ((NI) 0));
			LA58: ;
			if (!LOC57) goto LA62;
			(*info).weekday = ((NU8) 6);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA62: ;
		{
			NIM_BOOL LOC65;
			Slice88061 LOC67;
			NimStringDesc* LOC68;
			NI LOC69;
			LOC65 = 0;
			LOC65 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC65)) goto LA66;
			LOC67 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 5)));
			LOC68 = 0;
			LOC68 = HEX5BHEX5D_88054(value, LOC67);
			LOC69 = 0;
			LOC69 = nsuCmpIgnoreCase(LOC68, ((NimStringDesc*) &TMP234));
			LOC65 = (LOC69 == ((NI) 0));
			LA66: ;
			if (!LOC65) goto LA70;
			(*info).weekday = ((NU8) 0);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA70: ;
		{
			NIM_BOOL LOC73;
			Slice88061 LOC75;
			NimStringDesc* LOC76;
			NI LOC77;
			LOC73 = 0;
			LOC73 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC73)) goto LA74;
			LOC75 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 6)));
			LOC76 = 0;
			LOC76 = HEX5BHEX5D_88054(value, LOC75);
			LOC77 = 0;
			LOC77 = nsuCmpIgnoreCase(LOC76, ((NimStringDesc*) &TMP235));
			LOC73 = (LOC77 == ((NI) 0));
			LA74: ;
			if (!LOC73) goto LA78;
			(*info).weekday = ((NU8) 1);
			(*j) += ((NI) 7);
		}
		goto LA55;
		LA78: ;
		{
			NIM_BOOL LOC81;
			Slice88061 LOC83;
			NimStringDesc* LOC84;
			NI LOC85;
			LOC81 = 0;
			LOC81 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC81)) goto LA82;
			LOC83 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 8)));
			LOC84 = 0;
			LOC84 = HEX5BHEX5D_88054(value, LOC83);
			LOC85 = 0;
			LOC85 = nsuCmpIgnoreCase(LOC84, ((NimStringDesc*) &TMP236));
			LOC81 = (LOC85 == ((NI) 0));
			LA82: ;
			if (!LOC81) goto LA86;
			(*info).weekday = ((NU8) 2);
			(*j) += ((NI) 9);
		}
		goto LA55;
		LA86: ;
		{
			NIM_BOOL LOC89;
			Slice88061 LOC91;
			NimStringDesc* LOC92;
			NI LOC93;
			LOC89 = 0;
			LOC89 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC89)) goto LA90;
			LOC91 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 7)));
			LOC92 = 0;
			LOC92 = HEX5BHEX5D_88054(value, LOC91);
			LOC93 = 0;
			LOC93 = nsuCmpIgnoreCase(LOC92, ((NimStringDesc*) &TMP237));
			LOC89 = (LOC93 == ((NI) 0));
			LA90: ;
			if (!LOC89) goto LA94;
			(*info).weekday = ((NU8) 3);
			(*j) += ((NI) 8);
		}
		goto LA55;
		LA94: ;
		{
			NIM_BOOL LOC97;
			Slice88061 LOC99;
			NimStringDesc* LOC100;
			NI LOC101;
			LOC97 = 0;
			LOC97 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC97)) goto LA98;
			LOC99 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 5)));
			LOC100 = 0;
			LOC100 = HEX5BHEX5D_88054(value, LOC99);
			LOC101 = 0;
			LOC101 = nsuCmpIgnoreCase(LOC100, ((NimStringDesc*) &TMP238));
			LOC97 = (LOC101 == ((NI) 0));
			LA98: ;
			if (!LOC97) goto LA102;
			(*info).weekday = ((NU8) 4);
			(*j) += ((NI) 6);
		}
		goto LA55;
		LA102: ;
		{
			NIM_BOOL LOC105;
			Slice88061 LOC107;
			NimStringDesc* LOC108;
			NI LOC109;
			LOC105 = 0;
			LOC105 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC105)) goto LA106;
			LOC107 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 7)));
			LOC108 = 0;
			LOC108 = HEX5BHEX5D_88054(value, LOC107);
			LOC109 = 0;
			LOC109 = nsuCmpIgnoreCase(LOC108, ((NimStringDesc*) &TMP239));
			LOC105 = (LOC109 == ((NI) 0));
			LA106: ;
			if (!LOC105) goto LA110;
			(*info).weekday = ((NU8) 5);
			(*j) += ((NI) 8);
		}
		goto LA55;
		LA110: ;
		{
			Valueerror3449* e_109675;
			NimStringDesc* LOC113;
			e_109675 = 0;
			e_109675 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_109675).Sup.Sup.m_type = (&NTI3449);
			LOC113 = 0;
			LOC113 = (*e_109675).Sup.message; (*e_109675).Sup.message = copyStringRC1(((NimStringDesc*) &TMP232));
			if (LOC113) nimGCunrefNoCycle(LOC113);
			raiseException((Exception*)e_109675, "ValueError");
		}
		LA55: ;
	}
	goto LA24;
	LA5: ;
	{
		NI pd;
		Slice88061 LOC115;
		NimStringDesc* LOC116;
		LOC115 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC116 = 0;
		LOC116 = HEX5BHEX5D_88054(value, LOC115);
		pd = npuParseInt(LOC116, (&sv), ((NI) 0));
		(*info).hour = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA6: ;
	{
		Slice88061 LOC118;
		NimStringDesc* LOC119;
		NI LOC120;
		LOC118 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC119 = 0;
		LOC119 = HEX5BHEX5D_88054(value, LOC118);
		LOC120 = 0;
		LOC120 = nsuParseInt(LOC119);
		(*info).hour = ((NI) (LOC120));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA7: ;
	{
		NI pd;
		Slice88061 LOC122;
		NimStringDesc* LOC123;
		LOC122 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC123 = 0;
		LOC123 = HEX5BHEX5D_88054(value, LOC122);
		pd = npuParseInt(LOC123, (&sv), ((NI) 0));
		(*info).minute = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA8: ;
	{
		Slice88061 LOC125;
		NimStringDesc* LOC126;
		NI LOC127;
		LOC125 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC126 = 0;
		LOC126 = HEX5BHEX5D_88054(value, LOC125);
		LOC127 = 0;
		LOC127 = nsuParseInt(LOC126);
		(*info).minute = ((NI) (LOC127));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA9: ;
	{
		NI pd;
		Slice88061 LOC129;
		NimStringDesc* LOC130;
		LOC129 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC130 = 0;
		LOC130 = HEX5BHEX5D_88054(value, LOC129);
		pd = npuParseInt(LOC130, (&sv), ((NI) 0));
		(*info).month = ((NU8) ((NI)(sv - ((NI) 1))));
		(*info).monthday = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA10: ;
	{
		NI month;
		Slice88061 LOC132;
		NimStringDesc* LOC133;
		LOC132 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC133 = 0;
		LOC133 = HEX5BHEX5D_88054(value, LOC132);
		month = nsuParseInt(LOC133);
		(*j) += ((NI) 2);
		(*info).month = ((NU8) ((NI)(month - ((NI) 1))));
	}
	goto LA24;
	LA11: ;
	{
		Slice88061 LOC135;
		NimStringDesc* LOC136;
		NimStringDesc* LOC137;
		LOC135 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 2)));
		LOC136 = 0;
		LOC136 = HEX5BHEX5D_88054(value, LOC135);
		LOC137 = 0;
		LOC137 = nsuToLowerStr(LOC136);
		switch (hashString(LOC137) & 15) {
		case 0: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP241))) goto LA139;
break;
		case 3: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP242))) goto LA140;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP244))) goto LA142;
break;
		case 5: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP251))) goto LA149;
break;
		case 8: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP240))) goto LA138;
break;
		case 9: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP247))) goto LA145;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP248))) goto LA146;
break;
		case 11: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP245))) goto LA143;
break;
		case 14: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP243))) goto LA141;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP250))) goto LA148;
break;
		case 15: 
if (eqStrings(LOC137, ((NimStringDesc*) &TMP246))) goto LA144;
if (eqStrings(LOC137, ((NimStringDesc*) &TMP249))) goto LA147;
break;
		}
		goto LA150;
		LA138: ;
		{
			(*info).month = ((NU8) 0);
		}
		goto LA151;
		LA139: ;
		{
			(*info).month = ((NU8) 1);
		}
		goto LA151;
		LA140: ;
		{
			(*info).month = ((NU8) 2);
		}
		goto LA151;
		LA141: ;
		{
			(*info).month = ((NU8) 3);
		}
		goto LA151;
		LA142: ;
		{
			(*info).month = ((NU8) 4);
		}
		goto LA151;
		LA143: ;
		{
			(*info).month = ((NU8) 5);
		}
		goto LA151;
		LA144: ;
		{
			(*info).month = ((NU8) 6);
		}
		goto LA151;
		LA145: ;
		{
			(*info).month = ((NU8) 7);
		}
		goto LA151;
		LA146: ;
		{
			(*info).month = ((NU8) 8);
		}
		goto LA151;
		LA147: ;
		{
			(*info).month = ((NU8) 9);
		}
		goto LA151;
		LA148: ;
		{
			(*info).month = ((NU8) 10);
		}
		goto LA151;
		LA149: ;
		{
			(*info).month = ((NU8) 11);
		}
		goto LA151;
		LA150: ;
		{
			Valueerror3449* e_109818;
			NimStringDesc* LOC165;
			e_109818 = 0;
			e_109818 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_109818).Sup.Sup.m_type = (&NTI3449);
			LOC165 = 0;
			LOC165 = (*e_109818).Sup.message; (*e_109818).Sup.message = copyStringRC1(((NimStringDesc*) &TMP252));
			if (LOC165) nimGCunrefNoCycle(LOC165);
			raiseException((Exception*)e_109818, "ValueError");
		}
		LA151: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA12: ;
	{
		{
			NIM_BOOL LOC169;
			Slice88061 LOC171;
			NimStringDesc* LOC172;
			NI LOC173;
			LOC169 = 0;
			LOC169 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC169)) goto LA170;
			LOC171 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 6)));
			LOC172 = 0;
			LOC172 = HEX5BHEX5D_88054(value, LOC171);
			LOC173 = 0;
			LOC173 = nsuCmpIgnoreCase(LOC172, ((NimStringDesc*) &TMP253));
			LOC169 = (LOC173 == ((NI) 0));
			LA170: ;
			if (!LOC169) goto LA174;
			(*info).month = ((NU8) 0);
			(*j) += ((NI) 7);
		}
		goto LA167;
		LA174: ;
		{
			NIM_BOOL LOC177;
			Slice88061 LOC179;
			NimStringDesc* LOC180;
			NI LOC181;
			LOC177 = 0;
			LOC177 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC177)) goto LA178;
			LOC179 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 7)));
			LOC180 = 0;
			LOC180 = HEX5BHEX5D_88054(value, LOC179);
			LOC181 = 0;
			LOC181 = nsuCmpIgnoreCase(LOC180, ((NimStringDesc*) &TMP254));
			LOC177 = (LOC181 == ((NI) 0));
			LA178: ;
			if (!LOC177) goto LA182;
			(*info).month = ((NU8) 1);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA182: ;
		{
			NIM_BOOL LOC185;
			Slice88061 LOC187;
			NimStringDesc* LOC188;
			NI LOC189;
			LOC185 = 0;
			LOC185 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC185)) goto LA186;
			LOC187 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 4)));
			LOC188 = 0;
			LOC188 = HEX5BHEX5D_88054(value, LOC187);
			LOC189 = 0;
			LOC189 = nsuCmpIgnoreCase(LOC188, ((NimStringDesc*) &TMP255));
			LOC185 = (LOC189 == ((NI) 0));
			LA186: ;
			if (!LOC185) goto LA190;
			(*info).month = ((NU8) 2);
			(*j) += ((NI) 5);
		}
		goto LA167;
		LA190: ;
		{
			NIM_BOOL LOC193;
			Slice88061 LOC195;
			NimStringDesc* LOC196;
			NI LOC197;
			LOC193 = 0;
			LOC193 = ((NI)((*j) + ((NI) 5)) <= (value ? value->Sup.len : 0));
			if (!(LOC193)) goto LA194;
			LOC195 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 4)));
			LOC196 = 0;
			LOC196 = HEX5BHEX5D_88054(value, LOC195);
			LOC197 = 0;
			LOC197 = nsuCmpIgnoreCase(LOC196, ((NimStringDesc*) &TMP256));
			LOC193 = (LOC197 == ((NI) 0));
			LA194: ;
			if (!LOC193) goto LA198;
			(*info).month = ((NU8) 3);
			(*j) += ((NI) 5);
		}
		goto LA167;
		LA198: ;
		{
			NIM_BOOL LOC201;
			Slice88061 LOC203;
			NimStringDesc* LOC204;
			NI LOC205;
			LOC201 = 0;
			LOC201 = ((NI)((*j) + ((NI) 3)) <= (value ? value->Sup.len : 0));
			if (!(LOC201)) goto LA202;
			LOC203 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 2)));
			LOC204 = 0;
			LOC204 = HEX5BHEX5D_88054(value, LOC203);
			LOC205 = 0;
			LOC205 = nsuCmpIgnoreCase(LOC204, ((NimStringDesc*) &TMP244));
			LOC201 = (LOC205 == ((NI) 0));
			LA202: ;
			if (!LOC201) goto LA206;
			(*info).month = ((NU8) 4);
			(*j) += ((NI) 3);
		}
		goto LA167;
		LA206: ;
		{
			NIM_BOOL LOC209;
			Slice88061 LOC211;
			NimStringDesc* LOC212;
			NI LOC213;
			LOC209 = 0;
			LOC209 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC209)) goto LA210;
			LOC211 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 3)));
			LOC212 = 0;
			LOC212 = HEX5BHEX5D_88054(value, LOC211);
			LOC213 = 0;
			LOC213 = nsuCmpIgnoreCase(LOC212, ((NimStringDesc*) &TMP257));
			LOC209 = (LOC213 == ((NI) 0));
			LA210: ;
			if (!LOC209) goto LA214;
			(*info).month = ((NU8) 5);
			(*j) += ((NI) 4);
		}
		goto LA167;
		LA214: ;
		{
			NIM_BOOL LOC217;
			Slice88061 LOC219;
			NimStringDesc* LOC220;
			NI LOC221;
			LOC217 = 0;
			LOC217 = ((NI)((*j) + ((NI) 4)) <= (value ? value->Sup.len : 0));
			if (!(LOC217)) goto LA218;
			LOC219 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 3)));
			LOC220 = 0;
			LOC220 = HEX5BHEX5D_88054(value, LOC219);
			LOC221 = 0;
			LOC221 = nsuCmpIgnoreCase(LOC220, ((NimStringDesc*) &TMP258));
			LOC217 = (LOC221 == ((NI) 0));
			LA218: ;
			if (!LOC217) goto LA222;
			(*info).month = ((NU8) 6);
			(*j) += ((NI) 4);
		}
		goto LA167;
		LA222: ;
		{
			NIM_BOOL LOC225;
			Slice88061 LOC227;
			NimStringDesc* LOC228;
			NI LOC229;
			LOC225 = 0;
			LOC225 = ((NI)((*j) + ((NI) 6)) <= (value ? value->Sup.len : 0));
			if (!(LOC225)) goto LA226;
			LOC227 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 5)));
			LOC228 = 0;
			LOC228 = HEX5BHEX5D_88054(value, LOC227);
			LOC229 = 0;
			LOC229 = nsuCmpIgnoreCase(LOC228, ((NimStringDesc*) &TMP259));
			LOC225 = (LOC229 == ((NI) 0));
			LA226: ;
			if (!LOC225) goto LA230;
			(*info).month = ((NU8) 7);
			(*j) += ((NI) 6);
		}
		goto LA167;
		LA230: ;
		{
			NIM_BOOL LOC233;
			Slice88061 LOC235;
			NimStringDesc* LOC236;
			NI LOC237;
			LOC233 = 0;
			LOC233 = ((NI)((*j) + ((NI) 9)) <= (value ? value->Sup.len : 0));
			if (!(LOC233)) goto LA234;
			LOC235 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 8)));
			LOC236 = 0;
			LOC236 = HEX5BHEX5D_88054(value, LOC235);
			LOC237 = 0;
			LOC237 = nsuCmpIgnoreCase(LOC236, ((NimStringDesc*) &TMP260));
			LOC233 = (LOC237 == ((NI) 0));
			LA234: ;
			if (!LOC233) goto LA238;
			(*info).month = ((NU8) 8);
			(*j) += ((NI) 9);
		}
		goto LA167;
		LA238: ;
		{
			NIM_BOOL LOC241;
			Slice88061 LOC243;
			NimStringDesc* LOC244;
			NI LOC245;
			LOC241 = 0;
			LOC241 = ((NI)((*j) + ((NI) 7)) <= (value ? value->Sup.len : 0));
			if (!(LOC241)) goto LA242;
			LOC243 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 6)));
			LOC244 = 0;
			LOC244 = HEX5BHEX5D_88054(value, LOC243);
			LOC245 = 0;
			LOC245 = nsuCmpIgnoreCase(LOC244, ((NimStringDesc*) &TMP261));
			LOC241 = (LOC245 == ((NI) 0));
			LA242: ;
			if (!LOC241) goto LA246;
			(*info).month = ((NU8) 9);
			(*j) += ((NI) 7);
		}
		goto LA167;
		LA246: ;
		{
			NIM_BOOL LOC249;
			Slice88061 LOC251;
			NimStringDesc* LOC252;
			NI LOC253;
			LOC249 = 0;
			LOC249 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC249)) goto LA250;
			LOC251 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 7)));
			LOC252 = 0;
			LOC252 = HEX5BHEX5D_88054(value, LOC251);
			LOC253 = 0;
			LOC253 = nsuCmpIgnoreCase(LOC252, ((NimStringDesc*) &TMP262));
			LOC249 = (LOC253 == ((NI) 0));
			LA250: ;
			if (!LOC249) goto LA254;
			(*info).month = ((NU8) 10);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA254: ;
		{
			NIM_BOOL LOC257;
			Slice88061 LOC259;
			NimStringDesc* LOC260;
			NI LOC261;
			LOC257 = 0;
			LOC257 = ((NI)((*j) + ((NI) 8)) <= (value ? value->Sup.len : 0));
			if (!(LOC257)) goto LA258;
			LOC259 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 7)));
			LOC260 = 0;
			LOC260 = HEX5BHEX5D_88054(value, LOC259);
			LOC261 = 0;
			LOC261 = nsuCmpIgnoreCase(LOC260, ((NimStringDesc*) &TMP263));
			LOC257 = (LOC261 == ((NI) 0));
			LA258: ;
			if (!LOC257) goto LA262;
			(*info).month = ((NU8) 11);
			(*j) += ((NI) 8);
		}
		goto LA167;
		LA262: ;
		{
			Valueerror3449* e_110067;
			NimStringDesc* LOC265;
			e_110067 = 0;
			e_110067 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_110067).Sup.Sup.m_type = (&NTI3449);
			LOC265 = 0;
			LOC265 = (*e_110067).Sup.message; (*e_110067).Sup.message = copyStringRC1(((NimStringDesc*) &TMP252));
			if (LOC265) nimGCunrefNoCycle(LOC265);
			raiseException((Exception*)e_110067, "ValueError");
		}
		LA167: ;
	}
	goto LA24;
	LA13: ;
	{
		NI pd;
		Slice88061 LOC267;
		NimStringDesc* LOC268;
		LOC267 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC268 = 0;
		LOC268 = HEX5BHEX5D_88054(value, LOC267);
		pd = npuParseInt(LOC268, (&sv), ((NI) 0));
		(*info).second = ((NI) (sv));
		(*j) += pd;
	}
	goto LA24;
	LA14: ;
	{
		Slice88061 LOC270;
		NimStringDesc* LOC271;
		NI LOC272;
		LOC270 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC271 = 0;
		LOC271 = HEX5BHEX5D_88054(value, LOC270);
		LOC272 = 0;
		LOC272 = nsuParseInt(LOC271);
		(*info).second = ((NI) (LOC272));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA15: ;
	{
		{
			NIM_BOOL LOC276;
			NIM_BOOL LOC277;
			LOC276 = 0;
			LOC277 = 0;
			LOC277 = ((NU8)(value->data[(*j)]) == (NU8)(80));
			if (!(LOC277)) goto LA278;
			LOC277 = (((NI) 0) < ((NI) ((*info).hour)));
			LA278: ;
			LOC276 = LOC277;
			if (!(LOC276)) goto LA279;
			LOC276 = (((NI) ((*info).hour)) < ((NI) 12));
			LA279: ;
			if (!LOC276) goto LA280;
			(*info).hour += ((NI) 12);
		}
		LA280: ;
		(*j) += ((NI) 1);
	}
	goto LA24;
	LA16: ;
	{
		{
			NIM_BOOL LOC285;
			NIM_BOOL LOC286;
			Slice88061 LOC287;
			NimStringDesc* LOC288;
			LOC285 = 0;
			LOC286 = 0;
			LOC287 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
			LOC288 = 0;
			LOC288 = HEX5BHEX5D_88054(value, LOC287);
			LOC286 = eqStrings(LOC288, ((NimStringDesc*) &TMP210));
			if (!(LOC286)) goto LA289;
			LOC286 = (((NI) 0) < ((NI) ((*info).hour)));
			LA289: ;
			LOC285 = LOC286;
			if (!(LOC285)) goto LA290;
			LOC285 = (((NI) ((*info).hour)) < ((NI) 12));
			LA290: ;
			if (!LOC285) goto LA291;
			(*info).hour += ((NI) 12);
		}
		LA291: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA17: ;
	{
		NI year;
		Slice88061 LOC294;
		NimStringDesc* LOC295;
		NI thiscen;
		time_t LOC296;
		Timeinfo107405 LOC297;
		LOC294 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 1)));
		LOC295 = 0;
		LOC295 = HEX5BHEX5D_88054(value, LOC294);
		year = nsuParseInt(LOC295);
		LOC296 = 0;
		LOC296 = gettime_107448();
		memset((void*)(&LOC297), 0, sizeof(LOC297));
		LOC297.Sup.m_type = (&NTI107405);
		getlocaltime_107453(LOC296, (&LOC297));
		thiscen = (NI)(((NI) (LOC297.year)) / ((NI) 100));
		(*info).year = ((NI) ((NI)(((NI) ((NI)(((NI) (thiscen)) * ((NI) 100)))) + year)));
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA18: ;
	{
		Slice88061 LOC299;
		NimStringDesc* LOC300;
		NI LOC301;
		LOC299 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 3)));
		LOC300 = 0;
		LOC300 = HEX5BHEX5D_88054(value, LOC299);
		LOC301 = 0;
		LOC301 = nsuParseInt(LOC300);
		(*info).year = ((NI) (LOC301));
		(*j) += ((NI) 4);
	}
	goto LA24;
	LA19: ;
	{
		{
			NimStringDesc* LOC307;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA305;
			LOC307 = 0;
			LOC307 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			(*info).timezone = nsuParseInt(LOC307);
		}
		goto LA303;
		LA305: ;
		{
			NimStringDesc* LOC311;
			NI LOC312;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA309;
			LOC311 = 0;
			LOC311 = nimCharToStr(value->data[(NI)((*j) + ((NI) 1))]);
			LOC312 = 0;
			LOC312 = nsuParseInt(LOC311);
			(*info).timezone = (NI)(((NI) 0) - LOC312);
		}
		goto LA303;
		LA309: ;
		{
			Valueerror3449* e_110209;
			NimStringDesc* LOC314;
			e_110209 = 0;
			e_110209 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_110209).Sup.Sup.m_type = (&NTI3449);
			LOC314 = 0;
			LOC314 = rawNewString(19);
appendString(LOC314, ((NimStringDesc*) &TMP264));
appendChar(LOC314, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_110209).Sup.message), LOC314);
			raiseException((Exception*)e_110209, "ValueError");
		}
		LA303: ;
		(*j) += ((NI) 2);
	}
	goto LA24;
	LA20: ;
	{
		{
			Slice88061 LOC320;
			NimStringDesc* LOC321;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA318;
			LOC320 = HEX2EHEX2E_109273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC321 = 0;
			LOC321 = HEX5BHEX5D_88054(value, LOC320);
			(*info).timezone = nsuParseInt(LOC321);
		}
		goto LA316;
		LA318: ;
		{
			Slice88061 LOC325;
			NimStringDesc* LOC326;
			NI LOC327;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA323;
			LOC325 = HEX2EHEX2E_109273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC326 = 0;
			LOC326 = HEX5BHEX5D_88054(value, LOC325);
			LOC327 = 0;
			LOC327 = nsuParseInt(LOC326);
			(*info).timezone = (NI)(((NI) 0) - LOC327);
		}
		goto LA316;
		LA323: ;
		{
			Valueerror3449* e_110250;
			NimStringDesc* LOC329;
			e_110250 = 0;
			e_110250 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_110250).Sup.Sup.m_type = (&NTI3449);
			LOC329 = 0;
			LOC329 = rawNewString(19);
appendString(LOC329, ((NimStringDesc*) &TMP264));
appendChar(LOC329, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_110250).Sup.message), LOC329);
			raiseException((Exception*)e_110250, "ValueError");
		}
		LA316: ;
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA21: ;
	{
		{
			Slice88061 LOC335;
			NimStringDesc* LOC336;
			if (!((NU8)(value->data[(*j)]) == (NU8)(43))) goto LA333;
			LOC335 = HEX2EHEX2E_109273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC336 = 0;
			LOC336 = HEX5BHEX5D_88054(value, LOC335);
			(*info).timezone = nsuParseInt(LOC336);
		}
		goto LA331;
		LA333: ;
		{
			Slice88061 LOC340;
			NimStringDesc* LOC341;
			NI LOC342;
			if (!((NU8)(value->data[(*j)]) == (NU8)(45))) goto LA338;
			LOC340 = HEX2EHEX2E_109273((NI)((*j) + ((NI) 1)), (NI)((*j) + ((NI) 2)));
			LOC341 = 0;
			LOC341 = HEX5BHEX5D_88054(value, LOC340);
			LOC342 = 0;
			LOC342 = nsuParseInt(LOC341);
			(*info).timezone = (NI)(((NI) 0) - LOC342);
		}
		goto LA331;
		LA338: ;
		{
			Valueerror3449* e_110291;
			NimStringDesc* LOC344;
			e_110291 = 0;
			e_110291 = (Valueerror3449*) newObj((&NTI22801), sizeof(Valueerror3449));
			(*e_110291).Sup.Sup.m_type = (&NTI3449);
			LOC344 = 0;
			LOC344 = rawNewString(19);
appendString(LOC344, ((NimStringDesc*) &TMP264));
appendChar(LOC344, value->data[(*j)]);
			asgnRefNoCycle((void**) (&(*e_110291).Sup.message), LOC344);
			raiseException((Exception*)e_110291, "ValueError");
		}
		LA331: ;
		(*j) += ((NI) 6);
	}
	goto LA24;
	LA22: ;
	{
		Slice88061 LOC346;
		NimStringDesc* LOC347;
		LOC346 = HEX2EHEX2E_109273((*j), (NI)((*j) + ((NI) 2)));
		LOC347 = 0;
		LOC347 = HEX5BHEX5D_88054(value, LOC346);
		unsureAsgnRef((void**) (&(*info).tzname), nsuToUpperStr(LOC347));
		(*j) += ((NI) 3);
	}
	goto LA24;
	LA23: ;
	{
		(*j) += (token ? token->Sup.len : 0);
	}
	LA24: ;
}

N_NIMCALL(void, parse_110352)(NimStringDesc* value, NimStringDesc* layout, Timeinfo107405* Result) {
	NI i;
	NI j;
	NimStringDesc* token;
	Timeinfo107405 info;
	time_t LOC1;
	time_t LOC30;
	Timeinfo107405 LOC31;
{	i = ((NI) 0);
	j = ((NI) 0);
	token = copyString(((NimStringDesc*) &TMP159));
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI107405);
	LOC1 = 0;
	LOC1 = gettime_107448();
	memset((void*)(&info), 0, sizeof(info));
	info.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC1, (&info));
	info.hour = ((NI) 0);
	info.minute = ((NI) 0);
	info.second = ((NI) 0);
	{
		while (1) {
			switch (((NU8)(layout->data[i]))) {
			case 32:
			case 45:
			case 47:
			case 58:
			case 39:
			case 0:
			case 40:
			case 41:
			case 91:
			case 93:
			case 44:
			{
				{
					if (!(((NI) 0) < (token ? token->Sup.len : 0))) goto LA7;
					parsetoken_109460((&info), token, value, (&j));
				}
				LA7: ;
				token = copyString(((NimStringDesc*) &TMP159));
				{
					if (!((NU8)(layout->data[i]) == (NU8)(0))) goto LA11;
					goto LA2;
				}
				LA11: ;
				{
					if (!((NU8)(layout->data[i]) == (NU8)(39))) goto LA15;
					i += ((NI) 1);
					j += ((NI) 1);
					{
						while (1) {
							NIM_BOOL LOC19;
							LOC19 = 0;
							LOC19 = !(((NU8)(layout->data[i]) == (NU8)(39)));
							if (!(LOC19)) goto LA20;
							LOC19 = (i < (NI)((layout ? layout->Sup.len : 0) - ((NI) 1)));
							LA20: ;
							if (!LOC19) goto LA18;
							i += ((NI) 1);
							j += ((NI) 1);
						} LA18: ;
					}
				}
				goto LA13;
				LA15: ;
				{
					i += ((NI) 1);
					j += ((NI) 1);
				}
				LA13: ;
			}
			break;
			default:
			{
				{
					NIM_BOOL LOC25;
					LOC25 = 0;
					LOC25 = ((token ? token->Sup.len : 0) < ((NI) 1));
					if (LOC25) goto LA26;
					LOC25 = ((NU8)(token->data[(token ? (token->Sup.len-1) : -1)]) == (NU8)(layout->data[i]));
					LA26: ;
					if (!LOC25) goto LA27;
					token = addChar(token, layout->data[i]);
					i += ((NI) 1);
				}
				goto LA23;
				LA27: ;
				{
					parsetoken_109460((&info), token, value, (&j));
					token = copyString(((NimStringDesc*) &TMP159));
				}
				LA23: ;
			}
			break;
			}
		}
	} LA2: ;
	LOC30 = 0;
	LOC30 = timeinfototime_107465((&info));
	memset((void*)(&LOC31), 0, sizeof(LOC31));
	LOC31.Sup.m_type = (&NTI107405);
	getlocaltime_107453(LOC30, (&LOC31));
	info.weekday = LOC31.weekday;
	genericAssign((void*)Result, (void*)(&info), (&NTI107405));
	goto BeforeRet;
	}BeforeRet: ;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void) {
static TNimNode* TMP151[11];
static TNimNode* TMP152[12];
NI TMP154;
static char* NIM_CONST TMP153[12] = {
"mJan", 
"mFeb", 
"mMar", 
"mApr", 
"mMay", 
"mJun", 
"mJul", 
"mAug", 
"mSep", 
"mOct", 
"mNov", 
"mDec"};
static TNimNode* TMP155[7];
NI TMP157;
static char* NIM_CONST TMP156[7] = {
"dMon", 
"dTue", 
"dWed", 
"dThu", 
"dFri", 
"dSat", 
"dSun"};
static TNimNode TMP141[33];
NTI107405.size = sizeof(Timeinfo107405);
NTI107405.kind = 17;
NTI107405.base = (&NTI3411);
TMP151[0] = &TMP141[1];
NTI107408.size = sizeof(NI);
NTI107408.kind = 20;
NTI107408.base = (&NTI108);
NTI107408.flags = 3;
TMP141[1].kind = 1;
TMP141[1].offset = offsetof(Timeinfo107405, second);
TMP141[1].typ = (&NTI107408);
TMP141[1].name = "second";
TMP151[1] = &TMP141[2];
NTI107410.size = sizeof(NI);
NTI107410.kind = 20;
NTI107410.base = (&NTI108);
NTI107410.flags = 3;
TMP141[2].kind = 1;
TMP141[2].offset = offsetof(Timeinfo107405, minute);
TMP141[2].typ = (&NTI107410);
TMP141[2].name = "minute";
TMP151[2] = &TMP141[3];
NTI107412.size = sizeof(NI);
NTI107412.kind = 20;
NTI107412.base = (&NTI108);
NTI107412.flags = 3;
TMP141[3].kind = 1;
TMP141[3].offset = offsetof(Timeinfo107405, hour);
TMP141[3].typ = (&NTI107412);
TMP141[3].name = "hour";
TMP151[3] = &TMP141[4];
NTI107415.size = sizeof(NI);
NTI107415.kind = 20;
NTI107415.base = (&NTI108);
NTI107415.flags = 3;
TMP141[4].kind = 1;
TMP141[4].offset = offsetof(Timeinfo107405, monthday);
TMP141[4].typ = (&NTI107415);
TMP141[4].name = "monthday";
TMP151[4] = &TMP141[5];
NTI104006.size = sizeof(NU8);
NTI104006.kind = 14;
NTI104006.base = 0;
NTI104006.flags = 3;
for (TMP154 = 0; TMP154 < 12; TMP154++) {
TMP141[TMP154+6].kind = 1;
TMP141[TMP154+6].offset = TMP154;
TMP141[TMP154+6].name = TMP153[TMP154];
TMP152[TMP154] = &TMP141[TMP154+6];
}
TMP141[18].len = 12; TMP141[18].kind = 2; TMP141[18].sons = &TMP152[0];
NTI104006.node = &TMP141[18];
TMP141[5].kind = 1;
TMP141[5].offset = offsetof(Timeinfo107405, month);
TMP141[5].typ = (&NTI104006);
TMP141[5].name = "month";
TMP151[5] = &TMP141[19];
NTI107418.size = sizeof(NI);
NTI107418.kind = 20;
NTI107418.base = (&NTI108);
NTI107418.flags = 3;
TMP141[19].kind = 1;
TMP141[19].offset = offsetof(Timeinfo107405, year);
TMP141[19].typ = (&NTI107418);
TMP141[19].name = "year";
TMP151[6] = &TMP141[20];
NTI104008.size = sizeof(NU8);
NTI104008.kind = 14;
NTI104008.base = 0;
NTI104008.flags = 3;
for (TMP157 = 0; TMP157 < 7; TMP157++) {
TMP141[TMP157+21].kind = 1;
TMP141[TMP157+21].offset = TMP157;
TMP141[TMP157+21].name = TMP156[TMP157];
TMP155[TMP157] = &TMP141[TMP157+21];
}
TMP141[28].len = 7; TMP141[28].kind = 2; TMP141[28].sons = &TMP155[0];
NTI104008.node = &TMP141[28];
TMP141[20].kind = 1;
TMP141[20].offset = offsetof(Timeinfo107405, weekday);
TMP141[20].typ = (&NTI104008);
TMP141[20].name = "weekday";
TMP151[7] = &TMP141[29];
NTI107424.size = sizeof(NI);
NTI107424.kind = 20;
NTI107424.base = (&NTI108);
NTI107424.flags = 3;
TMP141[29].kind = 1;
TMP141[29].offset = offsetof(Timeinfo107405, yearday);
TMP141[29].typ = (&NTI107424);
TMP141[29].name = "yearday";
TMP151[8] = &TMP141[30];
TMP141[30].kind = 1;
TMP141[30].offset = offsetof(Timeinfo107405, isdst);
TMP141[30].typ = (&NTI138);
TMP141[30].name = "isDST";
TMP151[9] = &TMP141[31];
TMP141[31].kind = 1;
TMP141[31].offset = offsetof(Timeinfo107405, tzname);
TMP141[31].typ = (&NTI149);
TMP141[31].name = "tzname";
TMP151[10] = &TMP141[32];
TMP141[32].kind = 1;
TMP141[32].offset = offsetof(Timeinfo107405, timezone);
TMP141[32].typ = (&NTI108);
TMP141[32].name = "timezone";
TMP141[0].len = 11; TMP141[0].kind = 2; TMP141[0].sons = &TMP151[0];
NTI107405.node = &TMP141[0];
}

