/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   g++.exe -c  -w -w -fpermissive  -IC:\Nim\lib -o c:\users\dansm\desktop\folders\robotics\field-telemetry\nimcache\telemetry.o c:\users\dansm\desktop\folders\robotics\field-telemetry\nimcache\telemetry.cpp */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <string.h>

#include <math.h>

#include <stdio.h>
struct Telemetry114013;
struct Row114008;
struct TGenericSeq;
struct TNimType;
struct TNimNode;
struct NimStringDesc;
struct Point114018;
struct Tcell46547;
struct Tcellseq46563;
struct Tgcheap48416;
struct Tcellset46559;
struct Tpagedesc46555;
struct Tmemregion28410;
struct Tsmallchunk27640;
struct Tllchunk28404;
struct Tbigchunk27642;
struct Tintset27617;
struct Ttrunk27613;
struct Tavlnode28408;
struct Tgcstat48414;
struct Tbasechunk27638;
struct Tfreecell27630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  NimStringDesc  : public TGenericSeq {
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Point114018  {
NI x;
NI y;
};
struct  Tcell46547  {
NI refcount;
TNimType* typ;
};
struct  Tcellseq46563  {
NI len;
NI cap;
Tcell46547** d;
};
struct  Tcellset46559  {
NI counter;
NI max;
Tpagedesc46555* head;
Tpagedesc46555** data;
};
typedef Tsmallchunk27640* TY28422[512];
typedef Ttrunk27613* Ttrunkbuckets27615[256];
struct  Tintset27617  {
Ttrunkbuckets27615 data;
};
struct  Tmemregion28410  {
NI minlargeobj;
NI maxlargeobj;
TY28422 freesmallchunks;
Tllchunk28404* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Tbigchunk27642* freechunkslist;
Tintset27617 chunkstarts;
Tavlnode28408* root;
Tavlnode28408* deleted;
Tavlnode28408* last;
Tavlnode28408* freeavlnodes;
};
struct  Tgcstat48414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Tgcheap48416  {
void* stackbottom;
NI cyclethreshold;
Tcellseq46563 zct;
Tcellseq46563 decstack;
Tcellset46559 cycleroots;
Tcellseq46563 tempstack;
NI recgclock;
Tmemregion28410 region;
Tgcstat48414 stat;
};
typedef NI TY27620[8];
struct  Tpagedesc46555  {
Tpagedesc46555* next;
NI key;
TY27620 bits;
};
struct  Tbasechunk27638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Tsmallchunk27640  : public Tbasechunk27638 {
Tsmallchunk27640* next;
Tsmallchunk27640* prev;
Tfreecell27630* freelist;
NI free;
NI acc;
NF data;
};
struct  Tllchunk28404  {
NI size;
NI acc;
Tllchunk28404* next;
};
struct  Tbigchunk27642  : public Tbasechunk27638 {
Tbigchunk27642* next;
Tbigchunk27642* prev;
NI align;
NF data;
};
struct  Ttrunk27613  {
Ttrunk27613* next;
NI key;
TY27620 bits;
};
typedef Tavlnode28408* TY28414[2];
struct  Tavlnode28408  {
TY28414 link;
NI key;
NI upperbound;
NI level;
};
struct  Tfreecell27630  {
Tfreecell27630* next;
NI zerofield;
};
struct Row114008 : TGenericSeq {
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Telemetry114013 : TGenericSeq {
  Row114008* data[SEQ_DECL_SIZE];
};
N_NIMCALL(Telemetry114013*, createtelemetry_114024)(NI xsize, NI ysize);
N_NIMCALL(void, TMP261)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP263)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src_83204, TNimType* mt);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, HEX24_114161)(Telemetry114013* telemetry);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, HEX24_114260)(Point114018 point);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(Telemetry114013*, set_114270)(Telemetry114013* telemetry, NI x, NI y, NIM_CHAR character);
N_NIMCALL(NI, xsize_114283)(Telemetry114013* telemetry);
N_NIMCALL(NI, ysize_114301)(Telemetry114013* telemetry);
N_NIMCALL(Telemetry114013*, drawlineabsolute_114367)(Telemetry114013* telemetry, Point114018 point1, Point114018 point2, NIM_CHAR character);
static N_INLINE(NF, HEX2F_87799)(NI x, NI y);
N_NIMCALL(Telemetry114013*, drawlinescaled_114483)(Telemetry114013* telemetry, NF x1, NF y1, NF x2, NF y2, NF centerx_114490, NF centery_114491, NF zoom, NIM_CHAR character);
N_NIMCALL(Telemetry114013*, drawwalls_114541)(Telemetry114013* telemetry, NF zoom);
N_NIMCALL(Telemetry114013*, drawfield_114583)(NF centerx, NF centery, NF zoom, NI xsize, NI ysize);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Tcell46547*, usrtocell_50047)(void* usr);
static N_INLINE(void, rtladdzct_51604)(Tcell46547* c);
N_NOINLINE(void, addzct_50017)(Tcellseq46563& s, Tcell46547* c);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, telemetryInit)(void);
NIM_EXTERNC N_NOINLINE(void, telemetryDatInit)(void);
STRING_LITERAL(TMP265, "", 0);
STRING_LITERAL(TMP267, "\015\012", 2);
STRING_LITERAL(TMP269, "x: ", 3);
STRING_LITERAL(TMP270, ", y: ", 5);
STRING_LITERAL(TMP278, "X: ", 3);
STRING_LITERAL(TMP279, " , Y: ", 6);
STRING_LITERAL(TMP282, "point 1: ", 9);
STRING_LITERAL(TMP283, "point 2: ", 9);
extern TNimType NTI147; /* char */
TNimType NTI114008; /* Row */
TNimType NTI114013; /* Telemetry */
extern TFrame* frameptr_17042;
Telemetry114013* field_114600;
extern Tgcheap48416 gch_48444;
NimStringDesc* i_114601;
N_NIMCALL(void, TMP261)(void* p, NI op) {
	Row114008* a;
	NI LOC1;
	a = (Row114008*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->len; LOC1++) {
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
{		goto BeforeRet;
}	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
{		goto BeforeRet;
}	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP263)(void* p, NI op) {
	Telemetry114013* a;
	NI LOC1;
	a = (Telemetry114013*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
{		LOC1 = ((NI) 0);
}	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
{		stackoverflow_19801();
}	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(Telemetry114013*, createtelemetry_114024)(NI xsize, NI ysize) {
	Telemetry114013* result;
	Row114008* row;
	nimfr("createTelemetry", "telemetry.nim")
	result = 0;
	nimln(17, "telemetry.nim");
	row = (Row114008*) newSeq((&NTI114008), 0);
	{
		NI i_114064;
		NI HEX3Atmp_114122;
		i_114064 = 0;
		HEX3Atmp_114122 = 0;
		nimln(18, "telemetry.nim");
		HEX3Atmp_114122 = subInt(xsize, 1);
		nimln(1598, "system.nim");
		NI res_114125 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP262;
				if (!(res_114125 <= HEX3Atmp_114122)) goto LA3;
				nimln(1600, "system.nim");
				i_114064 = res_114125;
				nimln(19, "telemetry.nim");
				row = (Row114008*) incrSeq(row, sizeof(NIM_CHAR));
				row->data[row->len-1] = 32;
				nimln(1619, "system.nim");
				TMP262 = addInt(res_114125, ((NI) 1));
				res_114125 = (NI)(TMP262);
			} LA3: ;
		}
	}
	nimln(21, "telemetry.nim");
	result = (Telemetry114013*) newSeq((&NTI114013), 0);
	{
		NI i_114109;
		NI HEX3Atmp_114130;
		i_114109 = 0;
		HEX3Atmp_114130 = 0;
		nimln(22, "telemetry.nim");
		HEX3Atmp_114130 = subInt(ysize, 1);
		nimln(1598, "system.nim");
		NI res_114133 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP264;
				if (!(res_114133 <= HEX3Atmp_114130)) goto LA6;
				nimln(1600, "system.nim");
				i_114109 = res_114133;
				nimln(23, "telemetry.nim");
				result = (Telemetry114013*) incrSeq(result, sizeof(Row114008*));
				genericSeqAssign((&result->data[result->len-1]), row, (&NTI114008));
				nimln(1619, "system.nim");
				TMP264 = addInt(res_114133, ((NI) 1));
				res_114133 = (NI)(TMP264);
			} LA6: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).len + ((NI) 1)));
	(*dest).len += (*src).len;
}

N_NIMCALL(NimStringDesc*, HEX24_114161)(Telemetry114013* telemetry) {
	NimStringDesc* result;
	NimStringDesc* mystring;
	nimfr("$", "telemetry.nim")
	result = 0;
	nimln(26, "telemetry.nim");
	mystring = copyString(((NimStringDesc*) &TMP265));
	{
		NI x_114192;
		NI HEX3Atmp_114229;
		x_114192 = 0;
		HEX3Atmp_114229 = 0;
		nimln(27, "telemetry.nim");
		HEX3Atmp_114229 = subInt((telemetry ? telemetry->len : 0), 1);
		nimln(1598, "system.nim");
		NI res_114232 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP268;
				if (!(res_114232 <= HEX3Atmp_114229)) goto LA3;
				nimln(1600, "system.nim");
				x_114192 = res_114232;
				{
					NI y_114219;
					NI HEX3Atmp_114222;
					y_114219 = 0;
					HEX3Atmp_114222 = 0;
					nimln(28, "telemetry.nim");
					if ((NU)(x_114192) >= (NU)(telemetry->len)) raiseIndexError();
					HEX3Atmp_114222 = subInt((telemetry->data[x_114192] ? telemetry->data[x_114192]->len : 0), 1);
					nimln(1598, "system.nim");
					NI res_114225 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP266;
							if (!(res_114225 <= HEX3Atmp_114222)) goto LA6;
							nimln(1600, "system.nim");
							y_114219 = res_114225;
							nimln(29, "telemetry.nim");
							if ((NU)(x_114192) >= (NU)(telemetry->len)) raiseIndexError();
							if ((NU)(y_114219) >= (NU)(telemetry->data[x_114192]->len)) raiseIndexError();
							mystring = addChar(mystring, telemetry->data[x_114192]->data[y_114219]);
							nimln(1619, "system.nim");
							TMP266 = addInt(res_114225, ((NI) 1));
							res_114225 = (NI)(TMP266);
						} LA6: ;
					}
				}
				nimln(30, "telemetry.nim");
				mystring = resizeString(mystring, 2);
appendString(mystring, ((NimStringDesc*) &TMP267));
				nimln(1619, "system.nim");
				TMP268 = addInt(res_114232, ((NI) 1));
				res_114232 = (NI)(TMP268);
			} LA3: ;
		}
	}
	nimln(31, "telemetry.nim");
	result = copyString(mystring);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX24_114260)(Point114018 point) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	NimStringDesc* LOC3;
	nimfr("$", "telemetry.nim")
	result = 0;
	nimln(34, "telemetry.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = nimIntToStr(point.x);
	LOC3 = 0;
	LOC3 = nimIntToStr(point.y);
	LOC1 = rawNewString(LOC2->len + LOC3->len + 8);
appendString(LOC1, ((NimStringDesc*) &TMP269));
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP270));
appendString(LOC1, LOC3);
	result = LOC1;
	popFrame();
	return result;
}

N_NIMCALL(Telemetry114013*, set_114270)(Telemetry114013* telemetry, NI x, NI y, NIM_CHAR character) {
	Telemetry114013* result;
	nimfr("set", "telemetry.nim")
	result = 0;
	nimln(37, "telemetry.nim");
	genericSeqAssign((&result), telemetry, (&NTI114013));
	nimln(38, "telemetry.nim");
	if ((NU)(y) >= (NU)(result->len)) raiseIndexError();
	if ((NU)(x) >= (NU)(result->data[y]->len)) raiseIndexError();
	result->data[y]->data[x] = character;
	popFrame();
	return result;
}

N_NIMCALL(NI, xsize_114283)(Telemetry114013* telemetry) {
	NI result;
	nimfr("xSize", "telemetry.nim")
	result = 0;
	nimln(41, "telemetry.nim");
	if ((NU)(((NI) 0)) >= (NU)(telemetry->len)) raiseIndexError();
	result = (telemetry->data[((NI) 0)] ? telemetry->data[((NI) 0)]->len : 0);
	popFrame();
	return result;
}

N_NIMCALL(NI, ysize_114301)(Telemetry114013* telemetry) {
	NI result;
	nimfr("ySize", "telemetry.nim")
	result = 0;
	nimln(44, "telemetry.nim");
	result = (telemetry ? telemetry->len : 0);
	popFrame();
	return result;
}

static N_INLINE(NF, HEX2F_87799)(NI x, NI y) {
	NF result;
	nimfr("/", "system.nim")
	result = 0;
	nimln(2856, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

N_NIMCALL(Telemetry114013*, drawlineabsolute_114367)(Telemetry114013* telemetry, Point114018 point1, Point114018 point2, NIM_CHAR character) {
	Telemetry114013* result;
	Point114018 LOC1;
	Point114018 LOC2;
	NF LOC3;
	nimfr("drawLineAbsolute", "telemetry.nim")
	result = 0;
	nimln(52, "telemetry.nim");
	genericSeqAssign((&result), telemetry, (&NTI114013));
	nimln(53, "telemetry.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.x = ((point1.x <= point2.x) ? point1.x : point2.x);
	LOC1.y = ((point1.y <= point2.y) ? point1.y : point2.y);
	Point114018 startpoint = LOC1;
	nimln(54, "telemetry.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.x = ((point1.x >= point2.x) ? point1.x : point2.x);
	LOC2.y = ((point1.y >= point2.y) ? point1.y : point2.y);
	Point114018 endpoint = LOC2;
	nimln(56, "telemetry.nim");
	LOC3 = 0;
	{
		NI TMP271;
		NI TMP272;
		NI TMP273;
		TMP271 = subInt(endpoint.x, startpoint.x);
		if (!!(((NI)(TMP271) == ((NI) 0)))) goto LA6;
{		TMP272 = subInt(endpoint.y, startpoint.y);
		TMP273 = subInt(endpoint.x, startpoint.x);
		LOC3 = HEX2F_87799((NI)(TMP272), (NI)(TMP273));
}	}
	goto LA4;
	LA6: ;
	{
		LOC3 = 5.0000000000000000e+006;
	}
	LA4: ;
	NF slope = LOC3;
	{
		NI y_114412;
		NI HEX3Atmp_114452;
		y_114412 = 0;
		HEX3Atmp_114452 = 0;
		nimln(58, "telemetry.nim");
		HEX3Atmp_114452 = subInt(endpoint.y, 1);
		nimln(1598, "system.nim");
		NI res_114455 = ((NI) 0);
		{
			nimln(1599, "system.nim");
			while (1) {
				NI TMP281;
				if (!(res_114455 <= HEX3Atmp_114452)) goto LA11;
				nimln(1600, "system.nim");
				y_114412 = res_114455;
				{
					NI x_114431;
					NI HEX3Atmp_114445;
					x_114431 = 0;
					HEX3Atmp_114445 = 0;
					nimln(59, "telemetry.nim");
					HEX3Atmp_114445 = subInt(endpoint.x, 1);
					nimln(1598, "system.nim");
					NI res_114448 = ((NI) 0);
					{
						nimln(1599, "system.nim");
						while (1) {
							NI TMP274;
							NI TMP275;
							NI TMP280;
							if (!(res_114448 <= HEX3Atmp_114445)) goto LA14;
							nimln(1600, "system.nim");
							x_114431 = res_114448;
							nimln(60, "telemetry.nim");
							TMP274 = subInt(y_114412, startpoint.y);
							NI idealx = lrint(((NF)(((NF)(((NF) ((NI)(TMP274)))) * (NF)(slope))) + (NF)(((NF) (startpoint.x)))));
							nimln(61, "telemetry.nim");
							TMP275 = subInt(x_114431, startpoint.x);
							NI idealy = lrint(((NF)(((NF)(((NF) ((NI)(TMP275)))) * (NF)(slope))) + (NF)(((NF) (startpoint.y)))));
							nimln(63, "telemetry.nim");
							{
								NIM_BOOL LOC17;
								NI TMP276;
								NI TMP277;
								NimStringDesc* LOC21;
								NimStringDesc* LOC22;
								NimStringDesc* LOC23;
								LOC17 = 0;
								TMP276 = subInt(idealy, y_114412);
								if ((NI)(TMP276) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
								LOC17 = (((NI)(TMP276) > 0? ((NI)(TMP276)) : -((NI)(TMP276))) < ((NI) 1));
								if (LOC17) goto LA18;
								TMP277 = subInt(idealx, x_114431);
								if ((NI)(TMP277) == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
								LOC17 = (((NI)(TMP277) > 0? ((NI)(TMP277)) : -((NI)(TMP277))) < ((NI) 1));
								LA18: ;
								if (!LOC17) goto LA19;
{								nimln(64, "telemetry.nim");
								LOC21 = 0;
								LOC22 = 0;
								LOC22 = nimIntToStr(x_114431);
								LOC23 = 0;
								LOC23 = nimIntToStr(y_114412);
								LOC21 = rawNewString(LOC22->len + LOC23->len + 9);
appendString(LOC21, ((NimStringDesc*) &TMP278));
appendString(LOC21, LOC22);
appendString(LOC21, ((NimStringDesc*) &TMP279));
appendString(LOC21, LOC23);
								printf("%s\015\012", LOC21? (LOC21)->data:"nil");
								nimln(65, "telemetry.nim");
								result = set_114270(result, x_114431, y_114412, character);
}							}
							LA19: ;
							nimln(1619, "system.nim");
							TMP280 = addInt(res_114448, ((NI) 1));
							res_114448 = (NI)(TMP280);
						} LA14: ;
					}
				}
				TMP281 = addInt(res_114455, ((NI) 1));
				res_114455 = (NI)(TMP281);
			} LA11: ;
		}
	}
	popFrame();
	return result;
}

N_NIMCALL(Telemetry114013*, drawlinescaled_114483)(Telemetry114013* telemetry, NF x1, NF y1, NF x2, NF y2, NF centerx_114490, NF centery_114491, NF zoom, NIM_CHAR character) {
	Telemetry114013* result;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	NI LOC4;
	NI LOC5;
	NI LOC6;
	NF LOC7;
	NF LOC8;
	NF LOC9;
	NF LOC10;
	Point114018 LOC11;
	Point114018 LOC12;
	NimStringDesc* LOC13;
	NimStringDesc* LOC14;
	NimStringDesc* LOC15;
	NimStringDesc* LOC16;
	nimfr("drawLineScaled", "telemetry.nim")
	result = 0;
	nimln(70, "telemetry.nim");
	LOC1 = 0;
	LOC1 = xsize_114283(telemetry);
	NF adjustedx1 = ((NF)(x1) * (NF)(((NF) (LOC1))));
	nimln(71, "telemetry.nim");
	LOC2 = 0;
	LOC2 = xsize_114283(telemetry);
	NF adjustedx2 = ((NF)(x2) * (NF)(((NF) (LOC2))));
	nimln(72, "telemetry.nim");
	LOC3 = 0;
	LOC3 = xsize_114283(telemetry);
	NF adjustedy1 = ((NF)(((NF)(1.0000000000000000e+000) - (NF)(y1))) * (NF)(((NF) (LOC3))));
	nimln(73, "telemetry.nim");
	LOC4 = 0;
	LOC4 = xsize_114283(telemetry);
	NF adjustedy2 = ((NF)(((NF)(1.0000000000000000e+000) - (NF)(y2))) * (NF)(((NF) (LOC4))));
	nimln(75, "telemetry.nim");
	LOC5 = 0;
	LOC5 = xsize_114283(telemetry);
	NF centerx = ((NF)(-(centerx_114490)) * (NF)(((NF) (LOC5))));
	nimln(76, "telemetry.nim");
	LOC6 = 0;
	LOC6 = xsize_114283(telemetry);
	NF centery = ((NF)(-(centery_114491)) * (NF)(((NF) (LOC6))));
	nimln(78, "telemetry.nim");
	LOC7 = 0;
	LOC7 = HEX2F_87799(xsize_114283(telemetry), ((NI) 2));
	NF realx1 = ((NF)(((NF)(((NF)(adjustedx1) - (NF)(centerx))) * (NF)(zoom))) - (NF)(LOC7));
	nimln(79, "telemetry.nim");
	LOC8 = 0;
	LOC8 = HEX2F_87799(xsize_114283(telemetry), ((NI) 2));
	NF realx2 = ((NF)(((NF)(((NF)(adjustedx2) - (NF)(centerx))) * (NF)(zoom))) - (NF)(LOC8));
	nimln(80, "telemetry.nim");
	LOC9 = 0;
	LOC9 = HEX2F_87799(xsize_114283(telemetry), ((NI) 2));
	NF realy1 = ((NF)(((NF)(((NF)(adjustedy1) - (NF)(centery))) * (NF)(zoom))) - (NF)(LOC9));
	nimln(81, "telemetry.nim");
	LOC10 = 0;
	LOC10 = HEX2F_87799(xsize_114283(telemetry), ((NI) 2));
	NF realy2 = ((NF)(((NF)(((NF)(adjustedy2) - (NF)(centery))) * (NF)(zoom))) - (NF)(LOC10));
	nimln(83, "telemetry.nim");
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	LOC11.x = ((NI) (realx1));
	LOC11.y = ((NI) (realy1));
	Point114018 point1 = LOC11;
	nimln(84, "telemetry.nim");
	memset((void*)(&LOC12), 0, sizeof(LOC12));
	LOC12.x = ((NI) (realx2));
	LOC12.y = ((NI) (realy2));
	Point114018 point2 = LOC12;
	nimln(86, "telemetry.nim");
	LOC13 = 0;
	LOC14 = 0;
	LOC14 = HEX24_114260(point1);
	LOC13 = rawNewString(LOC14->len + 9);
appendString(LOC13, ((NimStringDesc*) &TMP282));
appendString(LOC13, LOC14);
	printf("%s\015\012", LOC13? (LOC13)->data:"nil");
	nimln(87, "telemetry.nim");
	LOC15 = 0;
	LOC16 = 0;
	LOC16 = HEX24_114260(point2);
	LOC15 = rawNewString(LOC16->len + 9);
appendString(LOC15, ((NimStringDesc*) &TMP283));
appendString(LOC15, LOC16);
	printf("%s\015\012", LOC15? (LOC15)->data:"nil");
	nimln(90, "telemetry.nim");
	result = drawlineabsolute_114367(telemetry, point1, point2, character);
	popFrame();
	return result;
}

N_NIMCALL(Telemetry114013*, drawwalls_114541)(Telemetry114013* telemetry, NF zoom) {
	Telemetry114013* result;
	nimfr("drawWalls", "telemetry.nim")
	result = 0;
	nimln(94, "telemetry.nim");
	result = drawlinescaled_114483(telemetry, 0.0, 0.0, 1.0000000000000000e+000, 0.0, 5.0000000000000000e-001, 5.0000000000000000e-001, zoom, 35);
	nimln(95, "telemetry.nim");
	result = drawlinescaled_114483(result, 1.0000000000000000e+000, 1.0000000000000000e+000, 1.0000000000000000e+000, 0.0, 5.0000000000000000e-001, 5.0000000000000000e-001, zoom, 35);
	nimln(96, "telemetry.nim");
	result = drawlinescaled_114483(result, 0.0, 0.0, 0.0, 1.0000000000000000e+000, 5.0000000000000000e-001, 5.0000000000000000e-001, zoom, 35);
	nimln(97, "telemetry.nim");
	result = drawlinescaled_114483(result, 0.0, 1.0000000000000000e+000, 1.0000000000000000e+000, 1.0000000000000000e+000, 5.0000000000000000e-001, 5.0000000000000000e-001, zoom, 35);
	nimln(98, "telemetry.nim");
	result = drawlinescaled_114483(result, 0.0, 1.0000000000000000e+000, 1.0000000000000000e+000, 1.0000000000000000e+000, 5.0000000000000000e-001, 5.0000000000000000e-001, zoom, 35);
	popFrame();
	return result;
}

N_NIMCALL(Telemetry114013*, drawfield_114583)(NF centerx, NF centery, NF zoom, NI xsize, NI ysize) {
	Telemetry114013* result;
	nimfr("drawField", "telemetry.nim")
	result = 0;
	nimln(102, "telemetry.nim");
	result = drawwalls_114541(createtelemetry_114024(xsize, ysize), zoom);
	popFrame();
	return result;
}

static N_INLINE(Tcell46547*, usrtocell_50047)(void* usr) {
	Tcell46547* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	result = ((Tcell46547*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Tcell46547))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_51604)(Tcell46547* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_50017(gch_48444.zct, c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(251, "gc.nim");
	{
		if (!!((src == NIM_NIL))) goto LA3;
{		nimln(252, "gc.nim");
		Tcell46547* c = usrtocell_50047(src);
		nimln(169, "gc.nim");
		(*c).refcount += ((NI) 8);
}	}
	LA3: ;
	nimln(254, "gc.nim");
	{
		if (!!(((*dest) == NIM_NIL))) goto LA7;
{		nimln(255, "gc.nim");
		Tcell46547* c = usrtocell_50047((*dest));
		nimln(256, "gc.nim");
		{
			nimln(167, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(168, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
{			nimln(257, "gc.nim");
			rtladdzct_51604(c);
}		}
		LA11: ;
}	}
	LA7: ;
	nimln(258, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	Tcell46547* c = usrtocell_50047(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(168, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
{		nimln(236, "gc.nim");
		rtladdzct_51604(c);
}	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_winleanDatInit();
	stdlib_timesDatInit();
	stdlib_mathDatInit();
	telemetryDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_winleanInit();
	stdlib_timesInit();
	stdlib_mathInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	telemetryInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, telemetryInit)(void) {
	nimfr("telemetry", "telemetry.nim")
	nimln(105, "telemetry.nim");
	asgnRefNoCycle((void**) (&field_114600), drawfield_114583(1.0000000000000001e-001, 2.0000000000000001e-001, 1.0000000000000000e+000, ((NI) 30), ((NI) 30)));
	{
		{
			NI i_114805;
			NI HEX3Atmp_114807;
			NI LOC3;
			i_114805 = 0;
			HEX3Atmp_114807 = 0;
			nimln(47, "telemetry.nim");
			LOC3 = 0;
			LOC3 = ysize_114301(field_114600);
			HEX3Atmp_114807 = subInt(LOC3, 1);
			nimln(1598, "system.nim");
			NI res_114809 = ((NI) 0);
			{
				nimln(1599, "system.nim");
				while (1) {
					Row114008* row_114813;
					NimStringDesc* LOC6;
					NI TMP284;
					if (!(res_114809 <= HEX3Atmp_114807)) goto LA5;
					nimln(1600, "system.nim");
					i_114805 = res_114809;
					nimln(48, "telemetry.nim");
					if ((NU)(i_114805) >= (NU)(field_114600->len)) raiseIndexError();
					row_114813 = field_114600->data[i_114805];
					nimln(49, "telemetry.nim");
					LOC6 = 0;
					LOC6 = i_114601; i_114601 = copyStringRC1(((NimStringDesc*) (row_114813)));
					if (LOC6) nimGCunrefNoCycle(LOC6);
					nimln(107, "telemetry.nim");
					printf("%s\015\012", i_114601? (i_114601)->data:"nil");
					nimln(1619, "system.nim");
					TMP284 = addInt(res_114809, ((NI) 1));
					res_114809 = (NI)(TMP284);
				} LA5: ;
			}
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, telemetryDatInit)(void) {
NTI114008.size = sizeof(Row114008*);
NTI114008.kind = 24;
NTI114008.base = (&NTI147);
NTI114008.flags = 2;
NTI114008.marker = TMP261;
NTI114013.size = sizeof(Telemetry114013*);
NTI114013.kind = 24;
NTI114013.base = (&NTI114008);
NTI114013.flags = 2;
NTI114013.marker = TMP263;
}

